//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BrochureModelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BrochureModelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="BrochureModelDefiningFeatures" type="{http://schemas.configit.com/ace/import/v1/library}FeatureCodeCollection" minOccurs="0"/>
 *         &lt;element name="Derivatives" type="{http://schemas.configit.com/ace/import/v1/library}FeatureCodeCollection" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="Code" use="required" type="{http://schemas.configit.com/ace/import/v1}CodeType" />
 *       &lt;attribute name="Description" use="required" type="{http://schemas.configit.com/ace/import/v1}LimitedDescriptionType" />
 *       &lt;attribute name="Feature" use="required" type="{http://schemas.configit.com/ace/import/v1}CodeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BrochureModelType", namespace = "http://schemas.configit.com/ace/import/v1/productrange", propOrder = {

})
public class BrochureModelType {

    @XmlElement(name = "BrochureModelDefiningFeatures")
    protected FeatureCodeCollection brochureModelDefiningFeatures;
    @XmlElement(name = "Derivatives")
    protected FeatureCodeCollection derivatives;
    @XmlAttribute(name = "Code", required = true)
    protected String code;
    @XmlAttribute(name = "Description", required = true)
    protected String description;
    @XmlAttribute(name = "Feature", required = true)
    protected String feature;

    /**
     * Gets the value of the brochureModelDefiningFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureCodeCollection }
     *     
     */
    public FeatureCodeCollection getBrochureModelDefiningFeatures() {
        return brochureModelDefiningFeatures;
    }

    /**
     * Sets the value of the brochureModelDefiningFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureCodeCollection }
     *     
     */
    public void setBrochureModelDefiningFeatures(FeatureCodeCollection value) {
        this.brochureModelDefiningFeatures = value;
    }

    /**
     * Gets the value of the derivatives property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureCodeCollection }
     *     
     */
    public FeatureCodeCollection getDerivatives() {
        return derivatives;
    }

    /**
     * Sets the value of the derivatives property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureCodeCollection }
     *     
     */
    public void setDerivatives(FeatureCodeCollection value) {
        this.derivatives = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the feature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeature() {
        return feature;
    }

    /**
     * Sets the value of the feature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeature(String value) {
        this.feature = value;
    }

}
