//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BrochureModelDerivativeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BrochureModelDerivativeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="BrochureModel" use="required" type="{http://schemas.configit.com/ace/import/v1}CodeType" />
 *       &lt;attribute name="Derivative" use="required" type="{http://schemas.configit.com/ace/import/v1}CodeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BrochureModelDerivativeType", namespace = "http://schemas.configit.com/ace/import/v1/productrange")
public class BrochureModelDerivativeType {

    @XmlAttribute(name = "BrochureModel", required = true)
    protected String brochureModel;
    @XmlAttribute(name = "Derivative", required = true)
    protected String derivative;

    /**
     * Gets the value of the brochureModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrochureModel() {
        return brochureModel;
    }

    /**
     * Sets the value of the brochureModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrochureModel(String value) {
        this.brochureModel = value;
    }

    /**
     * Gets the value of the derivative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDerivative() {
        return derivative;
    }

    /**
     * Sets the value of the derivative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDerivative(String value) {
        this.derivative = value;
    }
    
    @Override
    public boolean equals(Object obj) {
    	if(obj instanceof BrochureModelDerivativeType){
    		BrochureModelDerivativeType f = (BrochureModelDerivativeType) obj;
    		return this.getBrochureModel().equals(f.getBrochureModel()) && this.getDerivative().equals(f.getDerivative());
    	}
    	return super.equals(obj);
    }
    
    @Override
    public int hashCode() {
    	// TODO Auto-generated method stub
    	return 1;
    }

}
