//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BuildPhaseTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BuildPhaseTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PreVolume"/>
 *     &lt;enumeration value="Volume"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BuildPhaseTypeEnum", namespace = "http://schemas.configit.com/ace/import/v1/productrange")
@XmlEnum
public enum BuildPhaseTypeEnum {

    @XmlEnumValue("PreVolume")
    PRE_VOLUME("PreVolume"),
    @XmlEnumValue("Volume")
    VOLUME("Volume");
    private final String value;

    BuildPhaseTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BuildPhaseTypeEnum fromValue(String v) {
        for (BuildPhaseTypeEnum c: BuildPhaseTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
