//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BuildPhaseMappingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BuildPhaseMappingType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.configit.com/ace/import/v1/productrange}EffectivityType">
 *       &lt;attribute name="Feature" use="required" type="{http://schemas.configit.com/ace/import/v1}CodeType" />
 *       &lt;attribute name="BuildPhaseType" use="required" type="{http://schemas.configit.com/ace/import/v1/productrange}BuildPhaseTypeEnum" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BuildPhaseMappingType", namespace = "http://schemas.configit.com/ace/import/v1/productrange")
public class BuildPhaseMappingType
    extends EffectivityType
{

    @XmlAttribute(name = "Feature", required = true)
    protected String feature;
    @XmlAttribute(name = "BuildPhaseType", required = true)
    protected BuildPhaseTypeEnum buildPhaseType;

    /**
     * Gets the value of the feature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeature() {
        return feature;
    }

    /**
     * Sets the value of the feature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeature(String value) {
        this.feature = value;
    }

    /**
     * Gets the value of the buildPhaseType property.
     * 
     * @return
     *     possible object is
     *     {@link BuildPhaseTypeEnum }
     *     
     */
    public BuildPhaseTypeEnum getBuildPhaseType() {
        return buildPhaseType;
    }

    /**
     * Sets the value of the buildPhaseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuildPhaseTypeEnum }
     *     
     */
    public void setBuildPhaseType(BuildPhaseTypeEnum value) {
        this.buildPhaseType = value;
    }

}
