//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConfigitAceImportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfigitAceImportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="ImportDetails" type="{http://schemas.configit.com/ace/import/v1}ImportDetailsType"/>
 *         &lt;element name="Metadata" type="{http://schemas.configit.com/ace/import/v1}MetadataType" minOccurs="0"/>
 *         &lt;element name="DataValidationOptions" type="{http://schemas.configit.com/ace/import/v1}DataValidationOptionsType" minOccurs="0"/>
 *         &lt;element name="PostImportValidationOptions" type="{http://schemas.configit.com/ace/import/v1}PostImportValidationOptionsType" minOccurs="0"/>
 *         &lt;element name="Library" type="{http://schemas.configit.com/ace/import/v1/library}LibraryType" minOccurs="0"/>
 *         &lt;element name="ProductRanges" type="{http://schemas.configit.com/ace/import/v1/productrange}ProductRangeCollection" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigitAceImportType", namespace = "http://schemas.configit.com/ace/import", propOrder = {
    "importDetails",
    "metadata",
    "dataValidationOptions",
    "postImportValidationOptions",
    "library",
    "productRanges"
})
@XmlRootElement(name = "ConfigitAceImportType")
public class ConfigitAceImportType {

    @XmlElement(name = "ImportDetails")
    protected ImportDetailsType importDetails;
    @XmlElement(name = "Metadata")
    protected MetadataType metadata;
    @XmlElement(name = "DataValidationOptions")
    protected DataValidationOptionsType dataValidationOptions;
    @XmlElement(name = "PostImportValidationOptions")
    protected PostImportValidationOptionsType postImportValidationOptions;
    @XmlElement(name = "Library")
    protected LibraryType library;
    @XmlElement(name = "ProductRanges")
    protected ProductRangeCollection productRanges;

    /**
     * Gets the value of the importDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ImportDetailsType }
     *     
     */
    public ImportDetailsType getImportDetails() {
        return importDetails;
    }

    /**
     * Sets the value of the importDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportDetailsType }
     *     
     */
    public void setImportDetails(ImportDetailsType value) {
        this.importDetails = value;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link MetadataType }
     *     
     */
    public MetadataType getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetadataType }
     *     
     */
    public void setMetadata(MetadataType value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the dataValidationOptions property.
     * 
     * @return
     *     possible object is
     *     {@link DataValidationOptionsType }
     *     
     */
    public DataValidationOptionsType getDataValidationOptions() {
        return dataValidationOptions;
    }

    /**
     * Sets the value of the dataValidationOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataValidationOptionsType }
     *     
     */
    public void setDataValidationOptions(DataValidationOptionsType value) {
        this.dataValidationOptions = value;
    }

    /**
     * Gets the value of the postImportValidationOptions property.
     * 
     * @return
     *     possible object is
     *     {@link PostImportValidationOptionsType }
     *     
     */
    public PostImportValidationOptionsType getPostImportValidationOptions() {
        return postImportValidationOptions;
    }

    /**
     * Sets the value of the postImportValidationOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostImportValidationOptionsType }
     *     
     */
    public void setPostImportValidationOptions(PostImportValidationOptionsType value) {
        this.postImportValidationOptions = value;
    }

    /**
     * Gets the value of the library property.
     * 
     * @return
     *     possible object is
     *     {@link LibraryType }
     *     
     */
    public LibraryType getLibrary() {
        return library;
    }

    /**
     * Sets the value of the library property.
     * 
     * @param value
     *     allowed object is
     *     {@link LibraryType }
     *     
     */
    public void setLibrary(LibraryType value) {
        this.library = value;
    }

    /**
     * Gets the value of the productRanges property.
     * 
     * @return
     *     possible object is
     *     {@link ProductRangeCollection }
     *     
     */
    public ProductRangeCollection getProductRanges() {
        return productRanges;
    }

    /**
     * Sets the value of the productRanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductRangeCollection }
     *     
     */
    public void setProductRanges(ProductRangeCollection value) {
        this.productRanges = value;
    }

}
