//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreateWorkItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateWorkItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="OnFailure" use="required" type="{http://schemas.configit.com/ace/import/v1}OnFailureEnum" />
 *       &lt;attribute name="OnSuccess" use="required" type="{http://schemas.configit.com/ace/import/v1}OnSuccessEnum" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateWorkItemType", namespace = "http://schemas.configit.com/ace/import/v1")
public class CreateWorkItemType {

    @XmlAttribute(name = "OnFailure", required = true)
    protected OnFailureEnum onFailure;
    @XmlAttribute(name = "OnSuccess", required = true)
    protected OnSuccessEnum onSuccess;

    /**
     * Gets the value of the onFailure property.
     * 
     * @return
     *     possible object is
     *     {@link OnFailureEnum }
     *     
     */
    public OnFailureEnum getOnFailure() {
        return onFailure;
    }

    /**
     * Sets the value of the onFailure property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnFailureEnum }
     *     
     */
    public void setOnFailure(OnFailureEnum value) {
        this.onFailure = value;
    }

    /**
     * Gets the value of the onSuccess property.
     * 
     * @return
     *     possible object is
     *     {@link OnSuccessEnum }
     *     
     */
    public OnSuccessEnum getOnSuccess() {
        return onSuccess;
    }

    /**
     * Sets the value of the onSuccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnSuccessEnum }
     *     
     */
    public void setOnSuccess(OnSuccessEnum value) {
        this.onSuccess = value;
    }

}
