//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataValidationOptionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataValidationOptionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="ModelYearMapping" type="{http://schemas.configit.com/ace/import/v1}ModelYearMappingValidationType" minOccurs="0"/>
 *         &lt;element name="Rule" type="{http://schemas.configit.com/ace/import/v1}RuleValidationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataValidationOptionsType", namespace = "http://schemas.configit.com/ace/import/v1", propOrder = {
    "modelYearMapping",
    "rule"
})
public class DataValidationOptionsType {

    @XmlElement(name = "ModelYearMapping")
    protected ModelYearMappingValidationType modelYearMapping;
    @XmlElement(name = "Rule")
    protected RuleValidationType rule;

    /**
     * Gets the value of the modelYearMapping property.
     * 
     * @return
     *     possible object is
     *     {@link ModelYearMappingValidationType }
     *     
     */
    public ModelYearMappingValidationType getModelYearMapping() {
        return modelYearMapping;
    }

    /**
     * Sets the value of the modelYearMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelYearMappingValidationType }
     *     
     */
    public void setModelYearMapping(ModelYearMappingValidationType value) {
        this.modelYearMapping = value;
    }

    /**
     * Gets the value of the rule property.
     * 
     * @return
     *     possible object is
     *     {@link RuleValidationType }
     *     
     */
    public RuleValidationType getRule() {
        return rule;
    }

    /**
     * Sets the value of the rule property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleValidationType }
     *     
     */
    public void setRule(RuleValidationType value) {
        this.rule = value;
    }

}
