//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DefaultConfiguratorLayoutType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DefaultConfiguratorLayoutType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ConfiguratorLayout" use="required" type="{http://schemas.configit.com/ace/import/v1}CodeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DefaultConfiguratorLayoutType", namespace = "http://schemas.configit.com/ace/import/v1/productrange")
public class DefaultConfiguratorLayoutType {

    @XmlAttribute(name = "ConfiguratorLayout", required = true)
    protected String configuratorLayout;

    /**
     * Gets the value of the configuratorLayout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfiguratorLayout() {
        return configuratorLayout;
    }

    /**
     * Sets the value of the configuratorLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfiguratorLayout(String value) {
        this.configuratorLayout = value;
    }

}
