//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FeatureApplicabilityInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeatureApplicabilityInfoType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.configit.com/ace/import/v1/library}FeatureCodeType">
 *       &lt;attribute name="Availability" use="required" type="{http://schemas.configit.com/ace/import/v1/productrange}AvailabilityEnum" />
 *       &lt;attribute name="MarketingValue" use="required" type="{http://schemas.configit.com/ace/import/v1/productrange}MarketingValueEnum" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeatureApplicabilityInfoType", namespace = "http://schemas.configit.com/ace/import/v1/productrange")
public class FeatureApplicabilityInfoType
    extends FeatureCodeType
{

    @XmlAttribute(name = "Availability", required = true)
    protected AvailabilityEnum availability;
    @XmlAttribute(name = "MarketingValue", required = true)
    protected MarketingValueEnum marketingValue;

    /**
     * Gets the value of the availability property.
     * 
     * @return
     *     possible object is
     *     {@link AvailabilityEnum }
     *     
     */
    public AvailabilityEnum getAvailability() {
        return availability;
    }

    /**
     * Sets the value of the availability property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailabilityEnum }
     *     
     */
    public void setAvailability(AvailabilityEnum value) {
        this.availability = value;
    }

    /**
     * Gets the value of the marketingValue property.
     * 
     * @return
     *     possible object is
     *     {@link MarketingValueEnum }
     *     
     */
    public MarketingValueEnum getMarketingValue() {
        return marketingValue;
    }

    /**
     * Sets the value of the marketingValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketingValueEnum }
     *     
     */
    public void setMarketingValue(MarketingValueEnum value) {
        this.marketingValue = value;
    }
    
    @Override
    public boolean equals(Object obj) {
    	if(obj instanceof FeatureApplicabilityInfoType){
    		FeatureApplicabilityInfoType f = (FeatureApplicabilityInfoType) obj;
    		return this.getAvailability().equals(f.getAvailability()) && this.getCode().equals(f.getCode()) && this.getMarketingValue().equals(f.getMarketingValue());
    	}
    	return super.equals(obj);
    }
    
    @Override
    public int hashCode() {
    	// TODO Auto-generated method stub
    	return 1;
    }

}
