//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FeatureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeatureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all minOccurs="0">
 *         &lt;element name="Descriptions" type="{http://schemas.configit.com/ace/import/v1/library}BrandDescriptionCollection"/>
 *         &lt;element name="CodeSetMappings" type="{http://schemas.configit.com/ace/import/v1/library}CodeSetMappingCollection"/>
 *         &lt;element name="PropertyValues" type="{http://schemas.configit.com/ace/import/v1}PropertyValueCollection"/>
 *       &lt;/all>
 *       &lt;attribute name="Code" use="required" type="{http://schemas.configit.com/ace/import/v1}CodeType" />
 *       &lt;attribute name="Description" use="required" type="{http://schemas.configit.com/ace/import/v1}DescriptionType" />
 *       &lt;attribute name="FeatureFamily" use="required" type="{http://schemas.configit.com/ace/import/v1}CodeType" />
 *       &lt;attribute name="Lifecycle" use="required" type="{http://schemas.configit.com/ace/import/v1/library}LifecycleEnum" />
 *       &lt;attribute name="SecurityLevel" use="required" type="{http://schemas.configit.com/ace/import/v1}SecurityLevelEnum" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeatureType", propOrder = {

})
public class FeatureType {

    @XmlElement(name = "Descriptions")
    protected BrandDescriptionCollection descriptions;
    @XmlElement(name = "CodeSetMappings")
    protected CodeSetMappingCollection codeSetMappings;
    @XmlElement(name = "PropertyValues")
    protected PropertyValueCollection propertyValues;
    @XmlAttribute(name = "Code", required = true)
    protected String code;
    @XmlAttribute(name = "Description", required = true)
    protected String description;
    @XmlAttribute(name = "FeatureFamily", required = true)
    protected String featureFamily;
    @XmlAttribute(name = "Lifecycle", required = true)
    protected LifecycleEnum lifecycle;
    @XmlAttribute(name = "SecurityLevel", required = true)
    protected SecurityLevelEnum securityLevel;

    /**
     * Gets the value of the descriptions property.
     * 
     * @return
     *     possible object is
     *     {@link BrandDescriptionCollection }
     *     
     */
    public BrandDescriptionCollection getDescriptions() {
        return descriptions;
    }

    /**
     * Sets the value of the descriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrandDescriptionCollection }
     *     
     */
    public void setDescriptions(BrandDescriptionCollection value) {
        this.descriptions = value;
    }

    /**
     * Gets the value of the codeSetMappings property.
     * 
     * @return
     *     possible object is
     *     {@link CodeSetMappingCollection }
     *     
     */
    public CodeSetMappingCollection getCodeSetMappings() {
        return codeSetMappings;
    }

    /**
     * Sets the value of the codeSetMappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeSetMappingCollection }
     *     
     */
    public void setCodeSetMappings(CodeSetMappingCollection value) {
        this.codeSetMappings = value;
    }

    /**
     * Gets the value of the propertyValues property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueCollection }
     *     
     */
    public PropertyValueCollection getPropertyValues() {
        return propertyValues;
    }

    /**
     * Sets the value of the propertyValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueCollection }
     *     
     */
    public void setPropertyValues(PropertyValueCollection value) {
        this.propertyValues = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the featureFamily property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureFamily() {
        return featureFamily;
    }

    /**
     * Sets the value of the featureFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureFamily(String value) {
        this.featureFamily = value;
    }

    /**
     * Gets the value of the lifecycle property.
     * 
     * @return
     *     possible object is
     *     {@link LifecycleEnum }
     *     
     */
    public LifecycleEnum getLifecycle() {
        return lifecycle;
    }

    /**
     * Sets the value of the lifecycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link LifecycleEnum }
     *     
     */
    public void setLifecycle(LifecycleEnum value) {
        this.lifecycle = value;
    }

    /**
     * Gets the value of the securityLevel property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityLevelEnum }
     *     
     */
    public SecurityLevelEnum getSecurityLevel() {
        return securityLevel;
    }

    /**
     * Sets the value of the securityLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityLevelEnum }
     *     
     */
    public void setSecurityLevel(SecurityLevelEnum value) {
        this.securityLevel = value;
    }

}
