//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FeatureFamilyTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FeatureFamilyTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Feature"/>
 *     &lt;enumeration value="Brand"/>
 *     &lt;enumeration value="Market"/>
 *     &lt;enumeration value="ProductRange"/>
 *     &lt;enumeration value="BrochureModel"/>
 *     &lt;enumeration value="ModelYear"/>
 *     &lt;enumeration value="Derivative"/>
 *     &lt;enumeration value="BuildPhase"/>
 *     &lt;enumeration value="Pack"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FeatureFamilyTypeEnum")
@XmlEnum
public enum FeatureFamilyTypeEnum {

    @XmlEnumValue("Feature")
    FEATURE("Feature"),
    @XmlEnumValue("Brand")
    BRAND("Brand"),
    @XmlEnumValue("Market")
    MARKET("Market"),
    @XmlEnumValue("ProductRange")
    PRODUCT_RANGE("ProductRange"),
    @XmlEnumValue("BrochureModel")
    BROCHURE_MODEL("BrochureModel"),
    @XmlEnumValue("ModelYear")
    MODEL_YEAR("ModelYear"),
    @XmlEnumValue("Derivative")
    DERIVATIVE("Derivative"),
    @XmlEnumValue("BuildPhase")
    BUILD_PHASE("BuildPhase"),
    @XmlEnumValue("Pack")
    PACK("Pack");
    private final String value;

    FeatureFamilyTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FeatureFamilyTypeEnum fromValue(String v) {
        for (FeatureFamilyTypeEnum c: FeatureFamilyTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
