//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LayoutFeatureFamilyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LayoutFeatureFamilyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all minOccurs="0">
 *         &lt;element name="LayoutFeatures" type="{http://schemas.configit.com/ace/import/v1/library}LayoutFeatureCollection" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="FeatureFamily" use="required" type="{http://schemas.configit.com/ace/import/v1}CodeType" />
 *       &lt;attribute name="CustomSort" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Position" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LayoutFeatureFamilyType", propOrder = {

})
public class LayoutFeatureFamilyType {

    @XmlElement(name = "LayoutFeatures")
    protected LayoutFeatureCollection layoutFeatures;
    @XmlAttribute(name = "FeatureFamily", required = true)
    protected String featureFamily;
    @XmlAttribute(name = "CustomSort", required = true)
    protected boolean customSort;
    @XmlAttribute(name = "Position", required = true)
    protected int position;

    /**
     * Gets the value of the layoutFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link LayoutFeatureCollection }
     *     
     */
    public LayoutFeatureCollection getLayoutFeatures() {
        return layoutFeatures;
    }

    /**
     * Sets the value of the layoutFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link LayoutFeatureCollection }
     *     
     */
    public void setLayoutFeatures(LayoutFeatureCollection value) {
        this.layoutFeatures = value;
    }

    /**
     * Gets the value of the featureFamily property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureFamily() {
        return featureFamily;
    }

    /**
     * Sets the value of the featureFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureFamily(String value) {
        this.featureFamily = value;
    }

    /**
     * Gets the value of the customSort property.
     * 
     */
    public boolean isCustomSort() {
        return customSort;
    }

    /**
     * Sets the value of the customSort property.
     * 
     */
    public void setCustomSort(boolean value) {
        this.customSort = value;
    }

    /**
     * Gets the value of the position property.
     * 
     */
    public int getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     */
    public void setPosition(int value) {
        this.position = value;
    }

}
