//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LayoutFeatureFamilyCollection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LayoutFeatureFamilyCollection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LayoutFeatureFamily" type="{http://schemas.configit.com/ace/import/v1/library}LayoutFeatureFamilyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LayoutFeatureFamilyCollection", propOrder = {
    "layoutFeatureFamily"
})
public class LayoutFeatureFamilyCollection {

    @XmlElement(name = "LayoutFeatureFamily")
    protected List<LayoutFeatureFamilyType> layoutFeatureFamily;

    /**
     * Gets the value of the layoutFeatureFamily property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the layoutFeatureFamily property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLayoutFeatureFamily().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LayoutFeatureFamilyType }
     * 
     * 
     */
    public List<LayoutFeatureFamilyType> getLayoutFeatureFamily() {
        if (layoutFeatureFamily == null) {
            layoutFeatureFamily = new ArrayList<LayoutFeatureFamilyType>();
        }
        return this.layoutFeatureFamily;
    }

}
