//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LayoutSectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LayoutSectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all minOccurs="0">
 *         &lt;element name="LayoutFeatureFamilies" type="{http://schemas.configit.com/ace/import/v1/library}LayoutFeatureFamilyCollection" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="Name" use="required" type="{http://schemas.configit.com/ace/import/v1}NameType" />
 *       &lt;attribute name="Position" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LayoutSectionType", propOrder = {

})
public class LayoutSectionType {

    @XmlElement(name = "LayoutFeatureFamilies")
    protected LayoutFeatureFamilyCollection layoutFeatureFamilies;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "Position", required = true)
    protected int position;

    /**
     * Gets the value of the layoutFeatureFamilies property.
     * 
     * @return
     *     possible object is
     *     {@link LayoutFeatureFamilyCollection }
     *     
     */
    public LayoutFeatureFamilyCollection getLayoutFeatureFamilies() {
        return layoutFeatureFamilies;
    }

    /**
     * Sets the value of the layoutFeatureFamilies property.
     * 
     * @param value
     *     allowed object is
     *     {@link LayoutFeatureFamilyCollection }
     *     
     */
    public void setLayoutFeatureFamilies(LayoutFeatureFamilyCollection value) {
        this.layoutFeatureFamilies = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the position property.
     * 
     */
    public int getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     */
    public void setPosition(int value) {
        this.position = value;
    }

}
