//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LibraryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LibraryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Properties" type="{http://schemas.configit.com/ace/import/v1/library}PropertyCollection" minOccurs="0"/>
 *         &lt;element name="CodeSets" type="{http://schemas.configit.com/ace/import/v1/library}CodeSetCollection" minOccurs="0"/>
 *         &lt;element name="Languages" type="{http://schemas.configit.com/ace/import/v1/library}LanguageCollection" minOccurs="0"/>
 *         &lt;element name="FeatureFamilies" type="{http://schemas.configit.com/ace/import/v1/library}FeatureFamilyCollection" minOccurs="0"/>
 *         &lt;element name="Features" type="{http://schemas.configit.com/ace/import/v1/library}FeatureCollection" minOccurs="0"/>
 *         &lt;element name="Brands" type="{http://schemas.configit.com/ace/import/v1/library}BrandCollection" minOccurs="0"/>
 *         &lt;element name="Markets" type="{http://schemas.configit.com/ace/import/v1/library}MarketCollection" minOccurs="0"/>
 *         &lt;element name="MarketGroups" type="{http://schemas.configit.com/ace/import/v1/library}MarketGroupCollection" minOccurs="0"/>
 *         &lt;element name="ConfiguratorLayouts" type="{http://schemas.configit.com/ace/import/v1/library}ConfiguratorLayoutCollection" minOccurs="0"/>
 *         &lt;element name="ProductGroups" type="{http://schemas.configit.com/ace/import/v1/library}ProductGroupCollection" minOccurs="0"/>
 *         &lt;element name="DeleteMarketGroups" type="{http://schemas.configit.com/ace/import/v1/delete}DeleteMarketGroupCollection" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LibraryType", propOrder = {
    "properties",
    "codeSets",
    "languages",
    "featureFamilies",
    "features",
    "brands",
    "markets",
    "marketGroups",
    "configuratorLayouts",
    "productGroups",
    "deleteMarketGroups"
})
public class LibraryType {

    @XmlElement(name = "Properties")
    protected PropertyCollection properties;
    @XmlElement(name = "CodeSets")
    protected CodeSetCollection codeSets;
    @XmlElement(name = "Languages")
    protected LanguageCollection languages;
    @XmlElement(name = "FeatureFamilies")
    protected FeatureFamilyCollection featureFamilies;
    @XmlElement(name = "Features")
    protected FeatureCollection features;
    @XmlElement(name = "Brands")
    protected BrandCollection brands;
    @XmlElement(name = "Markets")
    protected MarketCollection markets;
    @XmlElement(name = "MarketGroups")
    protected MarketGroupCollection marketGroups;
    @XmlElement(name = "ConfiguratorLayouts")
    protected ConfiguratorLayoutCollection configuratorLayouts;
    @XmlElement(name = "ProductGroups")
    protected ProductGroupCollection productGroups;
    @XmlElement(name = "DeleteMarketGroups")
    protected DeleteMarketGroupCollection deleteMarketGroups;

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyCollection }
     *     
     */
    public PropertyCollection getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyCollection }
     *     
     */
    public void setProperties(PropertyCollection value) {
        this.properties = value;
    }

    /**
     * Gets the value of the codeSets property.
     * 
     * @return
     *     possible object is
     *     {@link CodeSetCollection }
     *     
     */
    public CodeSetCollection getCodeSets() {
        return codeSets;
    }

    /**
     * Sets the value of the codeSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeSetCollection }
     *     
     */
    public void setCodeSets(CodeSetCollection value) {
        this.codeSets = value;
    }

    /**
     * Gets the value of the languages property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageCollection }
     *     
     */
    public LanguageCollection getLanguages() {
        return languages;
    }

    /**
     * Sets the value of the languages property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageCollection }
     *     
     */
    public void setLanguages(LanguageCollection value) {
        this.languages = value;
    }

    /**
     * Gets the value of the featureFamilies property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureFamilyCollection }
     *     
     */
    public FeatureFamilyCollection getFeatureFamilies() {
        return featureFamilies;
    }

    /**
     * Sets the value of the featureFamilies property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureFamilyCollection }
     *     
     */
    public void setFeatureFamilies(FeatureFamilyCollection value) {
        this.featureFamilies = value;
    }

    /**
     * Gets the value of the features property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureCollection }
     *     
     */
    public FeatureCollection getFeatures() {
        return features;
    }

    /**
     * Sets the value of the features property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureCollection }
     *     
     */
    public void setFeatures(FeatureCollection value) {
        this.features = value;
    }

    /**
     * Gets the value of the brands property.
     * 
     * @return
     *     possible object is
     *     {@link BrandCollection }
     *     
     */
    public BrandCollection getBrands() {
        return brands;
    }

    /**
     * Sets the value of the brands property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrandCollection }
     *     
     */
    public void setBrands(BrandCollection value) {
        this.brands = value;
    }

    /**
     * Gets the value of the markets property.
     * 
     * @return
     *     possible object is
     *     {@link MarketCollection }
     *     
     */
    public MarketCollection getMarkets() {
        return markets;
    }

    /**
     * Sets the value of the markets property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketCollection }
     *     
     */
    public void setMarkets(MarketCollection value) {
        this.markets = value;
    }

    /**
     * Gets the value of the marketGroups property.
     * 
     * @return
     *     possible object is
     *     {@link MarketGroupCollection }
     *     
     */
    public MarketGroupCollection getMarketGroups() {
        return marketGroups;
    }

    /**
     * Sets the value of the marketGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketGroupCollection }
     *     
     */
    public void setMarketGroups(MarketGroupCollection value) {
        this.marketGroups = value;
    }

    /**
     * Gets the value of the configuratorLayouts property.
     * 
     * @return
     *     possible object is
     *     {@link ConfiguratorLayoutCollection }
     *     
     */
    public ConfiguratorLayoutCollection getConfiguratorLayouts() {
        return configuratorLayouts;
    }

    /**
     * Sets the value of the configuratorLayouts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfiguratorLayoutCollection }
     *     
     */
    public void setConfiguratorLayouts(ConfiguratorLayoutCollection value) {
        this.configuratorLayouts = value;
    }

    /**
     * Gets the value of the productGroups property.
     * 
     * @return
     *     possible object is
     *     {@link ProductGroupCollection }
     *     
     */
    public ProductGroupCollection getProductGroups() {
        return productGroups;
    }

    /**
     * Sets the value of the productGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductGroupCollection }
     *     
     */
    public void setProductGroups(ProductGroupCollection value) {
        this.productGroups = value;
    }

    /**
     * Gets the value of the deleteMarketGroups property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteMarketGroupCollection }
     *     
     */
    public DeleteMarketGroupCollection getDeleteMarketGroups() {
        return deleteMarketGroups;
    }

    /**
     * Sets the value of the deleteMarketGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteMarketGroupCollection }
     *     
     */
    public void setDeleteMarketGroups(DeleteMarketGroupCollection value) {
        this.deleteMarketGroups = value;
    }

}
