//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LifecycleEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LifecycleEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Concept"/>
 *     &lt;enumeration value="Enabled"/>
 *     &lt;enumeration value="Retired"/>
 *     &lt;enumeration value="Obsolete"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LifecycleEnum")
@XmlEnum
public enum LifecycleEnum {

    @XmlEnumValue("Concept")
    CONCEPT("Concept"),
    @XmlEnumValue("Enabled")
    ENABLED("Enabled"),
    @XmlEnumValue("Retired")
    RETIRED("Retired"),
    @XmlEnumValue("Obsolete")
    OBSOLETE("Obsolete");
    private final String value;

    LifecycleEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LifecycleEnum fromValue(String v) {
        for (LifecycleEnum c: LifecycleEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
