//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MarketAvailabilityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarketAvailabilityType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.configit.com/ace/import/v1/productrange}EffectivityType">
 *       &lt;sequence>
 *         &lt;element name="AvailabilityRows" type="{http://schemas.configit.com/ace/import/v1/productrange}MarketAvailabilitySpanCollection"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarketAvailabilityType", namespace = "http://schemas.configit.com/ace/import/v1/productrange", propOrder = {
    "availabilityRows"
})
public class MarketAvailabilityType
    extends EffectivityType
{

    @XmlElement(name = "AvailabilityRows", required = true)
    protected MarketAvailabilitySpanCollection availabilityRows;

    /**
     * Gets the value of the availabilityRows property.
     * 
     * @return
     *     possible object is
     *     {@link MarketAvailabilitySpanCollection }
     *     
     */
    public MarketAvailabilitySpanCollection getAvailabilityRows() {
        return availabilityRows;
    }

    /**
     * Sets the value of the availabilityRows property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketAvailabilitySpanCollection }
     *     
     */
    public void setAvailabilityRows(MarketAvailabilitySpanCollection value) {
        this.availabilityRows = value;
    }

}
