//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MarketAvailabilitySpanType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarketAvailabilitySpanType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.configit.com/ace/import/v1/productrange}EffectivityType">
 *       &lt;sequence>
 *         &lt;element name="BrochureModelDerivatives" type="{http://schemas.configit.com/ace/import/v1/productrange}BrochureModelDerivativeCollection"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Market" use="required" type="{http://schemas.configit.com/ace/import/v1}CodeType" />
 *       &lt;attribute name="IsAvailable " use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarketAvailabilitySpanType", namespace = "http://schemas.configit.com/ace/import/v1/productrange", propOrder = {
    "brochureModelDerivatives"
})
public class MarketAvailabilitySpanType
    extends EffectivityType
{

    @XmlElement(name = "BrochureModelDerivatives", required = true)
    protected BrochureModelDerivativeCollection brochureModelDerivatives;
    @XmlAttribute(name = "Market", required = true)
    protected String market;
    @XmlAttribute(name = "IsAvailable ", required = true)
    protected boolean isAvailable0020;

    /**
     * Gets the value of the brochureModelDerivatives property.
     * 
     * @return
     *     possible object is
     *     {@link BrochureModelDerivativeCollection }
     *     
     */
    public BrochureModelDerivativeCollection getBrochureModelDerivatives() {
        return brochureModelDerivatives;
    }

    /**
     * Sets the value of the brochureModelDerivatives property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrochureModelDerivativeCollection }
     *     
     */
    public void setBrochureModelDerivatives(BrochureModelDerivativeCollection value) {
        this.brochureModelDerivatives = value;
    }

    /**
     * Gets the value of the market property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarket() {
        return market;
    }

    /**
     * Sets the value of the market property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarket(String value) {
        this.market = value;
    }

    /**
     * Gets the value of the isAvailable0020 property.
     * 
     */
    public boolean isIsAvailable_0020() {
        return isAvailable0020;
    }

    /**
     * Sets the value of the isAvailable0020 property.
     * 
     */
    public void setIsAvailable_0020(boolean value) {
        this.isAvailable0020 = value;
    }

}
