//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MarketGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarketGroupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all minOccurs="0">
 *         &lt;element name="PropertyValues" type="{http://schemas.configit.com/ace/import/v1}PropertyValueCollection" minOccurs="0"/>
 *         &lt;element name="Brands" type="{http://schemas.configit.com/ace/import/v1/library}BrandCodeCollection"/>
 *         &lt;element name="Markets" type="{http://schemas.configit.com/ace/import/v1/library}MarketCodeCollection"/>
 *       &lt;/all>
 *       &lt;attribute name="Code" use="required" type="{http://schemas.configit.com/ace/import/v1}CodeType" />
 *       &lt;attribute name="Description" use="required" type="{http://schemas.configit.com/ace/import/v1}DescriptionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarketGroupType", propOrder = {

})
public class MarketGroupType {

    @XmlElement(name = "PropertyValues")
    protected PropertyValueCollection propertyValues;
    @XmlElement(name = "Brands")
    protected BrandCodeCollection brands;
    @XmlElement(name = "Markets")
    protected MarketCodeCollection markets;
    @XmlAttribute(name = "Code", required = true)
    protected String code;
    @XmlAttribute(name = "Description", required = true)
    protected String description;

    /**
     * Gets the value of the propertyValues property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueCollection }
     *     
     */
    public PropertyValueCollection getPropertyValues() {
        return propertyValues;
    }

    /**
     * Sets the value of the propertyValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueCollection }
     *     
     */
    public void setPropertyValues(PropertyValueCollection value) {
        this.propertyValues = value;
    }

    /**
     * Gets the value of the brands property.
     * 
     * @return
     *     possible object is
     *     {@link BrandCodeCollection }
     *     
     */
    public BrandCodeCollection getBrands() {
        return brands;
    }

    /**
     * Sets the value of the brands property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrandCodeCollection }
     *     
     */
    public void setBrands(BrandCodeCollection value) {
        this.brands = value;
    }

    /**
     * Gets the value of the markets property.
     * 
     * @return
     *     possible object is
     *     {@link MarketCodeCollection }
     *     
     */
    public MarketCodeCollection getMarkets() {
        return markets;
    }

    /**
     * Sets the value of the markets property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketCodeCollection }
     *     
     */
    public void setMarkets(MarketCodeCollection value) {
        this.markets = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
