//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModelYearMappingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModelYearMappingType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.configit.com/ace/import/v1/productrange}EffectivityType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="BuildPhaseMappings" type="{http://schemas.configit.com/ace/import/v1/productrange}BuildPhaseMappingCollection" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Feature" use="required" type="{http://schemas.configit.com/ace/import/v1}CodeType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelYearMappingType", namespace = "http://schemas.configit.com/ace/import/v1/productrange", propOrder = {
    "buildPhaseMappings"
})
public class ModelYearMappingType
    extends EffectivityType
{

    @XmlElement(name = "BuildPhaseMappings")
    protected List<BuildPhaseMappingCollection> buildPhaseMappings;
    @XmlAttribute(name = "Feature", required = true)
    protected String feature;

    /**
     * Gets the value of the buildPhaseMappings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the buildPhaseMappings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBuildPhaseMappings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BuildPhaseMappingCollection }
     * 
     * 
     */
    public List<BuildPhaseMappingCollection> getBuildPhaseMappings() {
        if (buildPhaseMappings == null) {
            buildPhaseMappings = new ArrayList<BuildPhaseMappingCollection>();
        }
        return this.buildPhaseMappings;
    }

    /**
     * Gets the value of the feature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeature() {
        return feature;
    }

    /**
     * Sets the value of the feature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeature(String value) {
        this.feature = value;
    }

}
