//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sampleimport package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConfigitAceImport_QNAME = new QName("http://schemas.configit.com/ace/import", "ConfigitAceImport");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sampleimport
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConfigitAceImportType }
     * 
     */
    public ConfigitAceImportType createConfigitAceImportType() {
        return new ConfigitAceImportType();
    }

    /**
     * Create an instance of {@link CodeSetCollection }
     * 
     */
    public CodeSetCollection createCodeSetCollection() {
        return new CodeSetCollection();
    }

    /**
     * Create an instance of {@link PropertyCollection }
     * 
     */
    public PropertyCollection createPropertyCollection() {
        return new PropertyCollection();
    }

    /**
     * Create an instance of {@link FeatureCollection }
     * 
     */
    public FeatureCollection createFeatureCollection() {
        return new FeatureCollection();
    }

    /**
     * Create an instance of {@link ProductGroupCollection }
     * 
     */
    public ProductGroupCollection createProductGroupCollection() {
        return new ProductGroupCollection();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link MarketCodeType }
     * 
     */
    public MarketCodeType createMarketCodeType() {
        return new MarketCodeType();
    }

    /**
     * Create an instance of {@link LayoutFeatureCollection }
     * 
     */
    public LayoutFeatureCollection createLayoutFeatureCollection() {
        return new LayoutFeatureCollection();
    }

    /**
     * Create an instance of {@link FeatureType }
     * 
     */
    public FeatureType createFeatureType() {
        return new FeatureType();
    }

    /**
     * Create an instance of {@link FamilyCodeCollection }
     * 
     */
    public FamilyCodeCollection createFamilyCodeCollection() {
        return new FamilyCodeCollection();
    }

    /**
     * Create an instance of {@link BrandCodeType }
     * 
     */
    public BrandCodeType createBrandCodeType() {
        return new BrandCodeType();
    }

    /**
     * Create an instance of {@link FeatureCodeCollection }
     * 
     */
    public FeatureCodeCollection createFeatureCodeCollection() {
        return new FeatureCodeCollection();
    }

    /**
     * Create an instance of {@link BrandSpecificDataCollection }
     * 
     */
    public BrandSpecificDataCollection createBrandSpecificDataCollection() {
        return new BrandSpecificDataCollection();
    }

    /**
     * Create an instance of {@link MarketGroupCollection }
     * 
     */
    public MarketGroupCollection createMarketGroupCollection() {
        return new MarketGroupCollection();
    }

    /**
     * Create an instance of {@link MarketCollection }
     * 
     */
    public MarketCollection createMarketCollection() {
        return new MarketCollection();
    }

    /**
     * Create an instance of {@link LayoutFeatureFamilyCollection }
     * 
     */
    public LayoutFeatureFamilyCollection createLayoutFeatureFamilyCollection() {
        return new LayoutFeatureFamilyCollection();
    }

    /**
     * Create an instance of {@link MarketCodeCollection }
     * 
     */
    public MarketCodeCollection createMarketCodeCollection() {
        return new MarketCodeCollection();
    }

    /**
     * Create an instance of {@link LanguageCollection }
     * 
     */
    public LanguageCollection createLanguageCollection() {
        return new LanguageCollection();
    }

    /**
     * Create an instance of {@link CodeSetMappingCollection }
     * 
     */
    public CodeSetMappingCollection createCodeSetMappingCollection() {
        return new CodeSetMappingCollection();
    }

    /**
     * Create an instance of {@link ConfiguratorLayoutType }
     * 
     */
    public ConfiguratorLayoutType createConfiguratorLayoutType() {
        return new ConfiguratorLayoutType();
    }

    /**
     * Create an instance of {@link MarketGroupType }
     * 
     */
    public MarketGroupType createMarketGroupType() {
        return new MarketGroupType();
    }

    /**
     * Create an instance of {@link LayoutSectionCollection }
     * 
     */
    public LayoutSectionCollection createLayoutSectionCollection() {
        return new LayoutSectionCollection();
    }

    /**
     * Create an instance of {@link MarketLanguageCodeCollection }
     * 
     */
    public MarketLanguageCodeCollection createMarketLanguageCodeCollection() {
        return new MarketLanguageCodeCollection();
    }

    /**
     * Create an instance of {@link LibraryType }
     * 
     */
    public LibraryType createLibraryType() {
        return new LibraryType();
    }

    /**
     * Create an instance of {@link LayoutSectionType }
     * 
     */
    public LayoutSectionType createLayoutSectionType() {
        return new LayoutSectionType();
    }

    /**
     * Create an instance of {@link LanguageCodeType }
     * 
     */
    public LanguageCodeType createLanguageCodeType() {
        return new LanguageCodeType();
    }

    /**
     * Create an instance of {@link BrandSpecificDataType }
     * 
     */
    public BrandSpecificDataType createBrandSpecificDataType() {
        return new BrandSpecificDataType();
    }

    /**
     * Create an instance of {@link ConfiguratorLayoutCollection }
     * 
     */
    public ConfiguratorLayoutCollection createConfiguratorLayoutCollection() {
        return new ConfiguratorLayoutCollection();
    }

    /**
     * Create an instance of {@link LayoutTabCollection }
     * 
     */
    public LayoutTabCollection createLayoutTabCollection() {
        return new LayoutTabCollection();
    }

    /**
     * Create an instance of {@link BrandCodeCollection }
     * 
     */
    public BrandCodeCollection createBrandCodeCollection() {
        return new BrandCodeCollection();
    }

    /**
     * Create an instance of {@link LayoutTabType }
     * 
     */
    public LayoutTabType createLayoutTabType() {
        return new LayoutTabType();
    }

    /**
     * Create an instance of {@link FamilyCodeType }
     * 
     */
    public FamilyCodeType createFamilyCodeType() {
        return new FamilyCodeType();
    }

    /**
     * Create an instance of {@link BrandDescriptionCollection }
     * 
     */
    public BrandDescriptionCollection createBrandDescriptionCollection() {
        return new BrandDescriptionCollection();
    }

    /**
     * Create an instance of {@link LanguageCodeCollection }
     * 
     */
    public LanguageCodeCollection createLanguageCodeCollection() {
        return new LanguageCodeCollection();
    }

    /**
     * Create an instance of {@link FeatureCodeType }
     * 
     */
    public FeatureCodeType createFeatureCodeType() {
        return new FeatureCodeType();
    }

    /**
     * Create an instance of {@link LayoutFeatureFamilyType }
     * 
     */
    public LayoutFeatureFamilyType createLayoutFeatureFamilyType() {
        return new LayoutFeatureFamilyType();
    }

    /**
     * Create an instance of {@link BrandDescriptionType }
     * 
     */
    public BrandDescriptionType createBrandDescriptionType() {
        return new BrandDescriptionType();
    }

    /**
     * Create an instance of {@link BrandType }
     * 
     */
    public BrandType createBrandType() {
        return new BrandType();
    }

    /**
     * Create an instance of {@link LayoutFeatureType }
     * 
     */
    public LayoutFeatureType createLayoutFeatureType() {
        return new LayoutFeatureType();
    }

    /**
     * Create an instance of {@link MarketType }
     * 
     */
    public MarketType createMarketType() {
        return new MarketType();
    }

    /**
     * Create an instance of {@link FeatureFamilyCollection }
     * 
     */
    public FeatureFamilyCollection createFeatureFamilyCollection() {
        return new FeatureFamilyCollection();
    }

    /**
     * Create an instance of {@link FeatureFamilyType }
     * 
     */
    public FeatureFamilyType createFeatureFamilyType() {
        return new FeatureFamilyType();
    }

    /**
     * Create an instance of {@link BrandCollection }
     * 
     */
    public BrandCollection createBrandCollection() {
        return new BrandCollection();
    }

    /**
     * Create an instance of {@link MarketGroupCodeType }
     * 
     */
    public MarketGroupCodeType createMarketGroupCodeType() {
        return new MarketGroupCodeType();
    }

    /**
     * Create an instance of {@link ProductGroupType }
     * 
     */
    public ProductGroupType createProductGroupType() {
        return new ProductGroupType();
    }

    /**
     * Create an instance of {@link LanguageType }
     * 
     */
    public LanguageType createLanguageType() {
        return new LanguageType();
    }

    /**
     * Create an instance of {@link CodeSetType }
     * 
     */
    public CodeSetType createCodeSetType() {
        return new CodeSetType();
    }

    /**
     * Create an instance of {@link MarketGroupCodeCollection }
     * 
     */
    public MarketGroupCodeCollection createMarketGroupCodeCollection() {
        return new MarketGroupCodeCollection();
    }

    /**
     * Create an instance of {@link CodeSetMappingType }
     * 
     */
    public CodeSetMappingType createCodeSetMappingType() {
        return new CodeSetMappingType();
    }

    /**
     * Create an instance of {@link MetadataPropertyType }
     * 
     */
    public MetadataPropertyType createMetadataPropertyType() {
        return new MetadataPropertyType();
    }

    /**
     * Create an instance of {@link CodeCollection }
     * 
     */
    public CodeCollection createCodeCollection() {
        return new CodeCollection();
    }

    /**
     * Create an instance of {@link PropertyValueCollection }
     * 
     */
    public PropertyValueCollection createPropertyValueCollection() {
        return new PropertyValueCollection();
    }

    /**
     * Create an instance of {@link IntegerPropertyValueType }
     * 
     */
    public IntegerPropertyValueType createIntegerPropertyValueType() {
        return new IntegerPropertyValueType();
    }

    /**
     * Create an instance of {@link RuleValidationType }
     * 
     */
    public RuleValidationType createRuleValidationType() {
        return new RuleValidationType();
    }

    /**
     * Create an instance of {@link PreventPromotionIfMasterChangedType }
     * 
     */
    public PreventPromotionIfMasterChangedType createPreventPromotionIfMasterChangedType() {
        return new PreventPromotionIfMasterChangedType();
    }

    /**
     * Create an instance of {@link BooleanPropertyValueType }
     * 
     */
    public BooleanPropertyValueType createBooleanPropertyValueType() {
        return new BooleanPropertyValueType();
    }

    /**
     * Create an instance of {@link MetadataType }
     * 
     */
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link StringPropertyValueType }
     * 
     */
    public StringPropertyValueType createStringPropertyValueType() {
        return new StringPropertyValueType();
    }

    /**
     * Create an instance of {@link PropertyValueType }
     * 
     */
    public PropertyValueType createPropertyValueType() {
        return new PropertyValueType();
    }

    /**
     * Create an instance of {@link ModelYearMappingValidationType }
     * 
     */
    public ModelYearMappingValidationType createModelYearMappingValidationType() {
        return new ModelYearMappingValidationType();
    }

    /**
     * Create an instance of {@link DataValidationOptionsType }
     * 
     */
    public DataValidationOptionsType createDataValidationOptionsType() {
        return new DataValidationOptionsType();
    }

    /**
     * Create an instance of {@link ImportDetailsType }
     * 
     */
    public ImportDetailsType createImportDetailsType() {
        return new ImportDetailsType();
    }

    /**
     * Create an instance of {@link PostImportValidationOptionsType }
     * 
     */
    public PostImportValidationOptionsType createPostImportValidationOptionsType() {
        return new PostImportValidationOptionsType();
    }

    /**
     * Create an instance of {@link DateTimePropertyValueType }
     * 
     */
    public DateTimePropertyValueType createDateTimePropertyValueType() {
        return new DateTimePropertyValueType();
    }

    /**
     * Create an instance of {@link CreateWorkItemType }
     * 
     */
    public CreateWorkItemType createCreateWorkItemType() {
        return new CreateWorkItemType();
    }

    /**
     * Create an instance of {@link NotEmptyCodeCollection }
     * 
     */
    public NotEmptyCodeCollection createNotEmptyCodeCollection() {
        return new NotEmptyCodeCollection();
    }

    /**
     * Create an instance of {@link CompileProductRangesType }
     * 
     */
    public CompileProductRangesType createCompileProductRangesType() {
        return new CompileProductRangesType();
    }

    /**
     * Create an instance of {@link LongPropertyValueType }
     * 
     */
    public LongPropertyValueType createLongPropertyValueType() {
        return new LongPropertyValueType();
    }

    /**
     * Create an instance of {@link DecimalPropertyValueType }
     * 
     */
    public DecimalPropertyValueType createDecimalPropertyValueType() {
        return new DecimalPropertyValueType();
    }

    /**
     * Create an instance of {@link ShortPropertyValueType }
     * 
     */
    public ShortPropertyValueType createShortPropertyValueType() {
        return new ShortPropertyValueType();
    }

    /**
     * Create an instance of {@link DeleteModelYearMappingCollection }
     * 
     */
    public DeleteModelYearMappingCollection createDeleteModelYearMappingCollection() {
        return new DeleteModelYearMappingCollection();
    }

    /**
     * Create an instance of {@link DeleteRulesCollection }
     * 
     */
    public DeleteRulesCollection createDeleteRulesCollection() {
        return new DeleteRulesCollection();
    }

    /**
     * Create an instance of {@link DeleteModelYearMappingType }
     * 
     */
    public DeleteModelYearMappingType createDeleteModelYearMappingType() {
        return new DeleteModelYearMappingType();
    }

    /**
     * Create an instance of {@link DeleteMarketGroupCollection }
     * 
     */
    public DeleteMarketGroupCollection createDeleteMarketGroupCollection() {
        return new DeleteMarketGroupCollection();
    }

    /**
     * Create an instance of {@link DeleteRuleType }
     * 
     */
    public DeleteRuleType createDeleteRuleType() {
        return new DeleteRuleType();
    }

    /**
     * Create an instance of {@link DeleteMarketGroupType }
     * 
     */
    public DeleteMarketGroupType createDeleteMarketGroupType() {
        return new DeleteMarketGroupType();
    }

    /**
     * Create an instance of {@link TableRuleBodyRowType }
     * 
     */
    public TableRuleBodyRowType createTableRuleBodyRowType() {
        return new TableRuleBodyRowType();
    }

    /**
     * Create an instance of {@link ProductRangePropertiesType }
     * 
     */
    public ProductRangePropertiesType createProductRangePropertiesType() {
        return new ProductRangePropertiesType();
    }

    /**
     * Create an instance of {@link ProductRangeType }
     * 
     */
    public ProductRangeType createProductRangeType() {
        return new ProductRangeType();
    }

    /**
     * Create an instance of {@link PackRuleType }
     * 
     */
    public PackRuleType createPackRuleType() {
        return new PackRuleType();
    }

    /**
     * Create an instance of {@link BrochureModelDerivativeType }
     * 
     */
    public BrochureModelDerivativeType createBrochureModelDerivativeType() {
        return new BrochureModelDerivativeType();
    }

    /**
     * Create an instance of {@link FeatureApplicabilitySpanCollection }
     * 
     */
    public FeatureApplicabilitySpanCollection createFeatureApplicabilitySpanCollection() {
        return new FeatureApplicabilitySpanCollection();
    }

    /**
     * Create an instance of {@link ProductRangeCollection }
     * 
     */
    public ProductRangeCollection createProductRangeCollection() {
        return new ProductRangeCollection();
    }

    /**
     * Create an instance of {@link PackRuleIncludedFeatureType }
     * 
     */
    public PackRuleIncludedFeatureType createPackRuleIncludedFeatureType() {
        return new PackRuleIncludedFeatureType();
    }

    /**
     * Create an instance of {@link TextRuleType }
     * 
     */
    public TextRuleType createTextRuleType() {
        return new TextRuleType();
    }

    /**
     * Create an instance of {@link ModelYearMappingType }
     * 
     */
    public ModelYearMappingType createModelYearMappingType() {
        return new ModelYearMappingType();
    }

    /**
     * Create an instance of {@link TextRuleCollection }
     * 
     */
    public TextRuleCollection createTextRuleCollection() {
        return new TextRuleCollection();
    }

    /**
     * Create an instance of {@link BuildPhaseMappingCollection }
     * 
     */
    public BuildPhaseMappingCollection createBuildPhaseMappingCollection() {
        return new BuildPhaseMappingCollection();
    }

    /**
     * Create an instance of {@link RuleType }
     * 
     */
    public RuleType createRuleType() {
        return new RuleType();
    }

    /**
     * Create an instance of {@link PackRuleIncludedFeatureCollection }
     * 
     */
    public PackRuleIncludedFeatureCollection createPackRuleIncludedFeatureCollection() {
        return new PackRuleIncludedFeatureCollection();
    }

    /**
     * Create an instance of {@link ProductRangeFeatureAssociationType }
     * 
     */
    public ProductRangeFeatureAssociationType createProductRangeFeatureAssociationType() {
        return new ProductRangeFeatureAssociationType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link ProgrammeCollection }
     * 
     */
    public ProgrammeCollection createProgrammeCollection() {
        return new ProgrammeCollection();
    }

    /**
     * Create an instance of {@link PackRuleCollection }
     * 
     */
    public PackRuleCollection createPackRuleCollection() {
        return new PackRuleCollection();
    }

    /**
     * Create an instance of {@link BrochureModelType }
     * 
     */
    public BrochureModelType createBrochureModelType() {
        return new BrochureModelType();
    }

    /**
     * Create an instance of {@link EffectivityType }
     * 
     */
    public EffectivityType createEffectivityType() {
        return new EffectivityType();
    }

    /**
     * Create an instance of {@link ProductRangeFeatureAssociationCollection }
     * 
     */
    public ProductRangeFeatureAssociationCollection createProductRangeFeatureAssociationCollection() {
        return new ProductRangeFeatureAssociationCollection();
    }

    /**
     * Create an instance of {@link MarketAvailabilitySpanType }
     * 
     */
    public MarketAvailabilitySpanType createMarketAvailabilitySpanType() {
        return new MarketAvailabilitySpanType();
    }

    /**
     * Create an instance of {@link EventCollection }
     * 
     */
    public EventCollection createEventCollection() {
        return new EventCollection();
    }

    /**
     * Create an instance of {@link RuleHeaderType }
     * 
     */
    public RuleHeaderType createRuleHeaderType() {
        return new RuleHeaderType();
    }

    /**
     * Create an instance of {@link SellableUnitsType }
     * 
     */
    public SellableUnitsType createSellableUnitsType() {
        return new SellableUnitsType();
    }

    /**
     * Create an instance of {@link EffectivityCollection }
     * 
     */
    public EffectivityCollection createEffectivityCollection() {
        return new EffectivityCollection();
    }

    /**
     * Create an instance of {@link TableRuleCollection }
     * 
     */
    public TableRuleCollection createTableRuleCollection() {
        return new TableRuleCollection();
    }

    /**
     * Create an instance of {@link DefaultConfiguratorLayoutType }
     * 
     */
    public DefaultConfiguratorLayoutType createDefaultConfiguratorLayoutType() {
        return new DefaultConfiguratorLayoutType();
    }

    /**
     * Create an instance of {@link BasicsType }
     * 
     */
    public BasicsType createBasicsType() {
        return new BasicsType();
    }

    /**
     * Create an instance of {@link FeatureApplicabilityInfoCollection }
     * 
     */
    public FeatureApplicabilityInfoCollection createFeatureApplicabilityInfoCollection() {
        return new FeatureApplicabilityInfoCollection();
    }

    /**
     * Create an instance of {@link IncludedFamilyType }
     * 
     */
    public IncludedFamilyType createIncludedFamilyType() {
        return new IncludedFamilyType();
    }

    /**
     * Create an instance of {@link BrochureModelCollection }
     * 
     */
    public BrochureModelCollection createBrochureModelCollection() {
        return new BrochureModelCollection();
    }

    /**
     * Create an instance of {@link TableRuleBodyRowCellType }
     * 
     */
    public TableRuleBodyRowCellType createTableRuleBodyRowCellType() {
        return new TableRuleBodyRowCellType();
    }

    /**
     * Create an instance of {@link MarketAvailabilitySpanCollection }
     * 
     */
    public MarketAvailabilitySpanCollection createMarketAvailabilitySpanCollection() {
        return new MarketAvailabilitySpanCollection();
    }

    /**
     * Create an instance of {@link MarketAvailabilityType }
     * 
     */
    public MarketAvailabilityType createMarketAvailabilityType() {
        return new MarketAvailabilityType();
    }

    /**
     * Create an instance of {@link BuildPhaseMappingType }
     * 
     */
    public BuildPhaseMappingType createBuildPhaseMappingType() {
        return new BuildPhaseMappingType();
    }

    /**
     * Create an instance of {@link TableRuleType }
     * 
     */
    public TableRuleType createTableRuleType() {
        return new TableRuleType();
    }

    /**
     * Create an instance of {@link ProgrammeType }
     * 
     */
    public ProgrammeType createProgrammeType() {
        return new ProgrammeType();
    }

    /**
     * Create an instance of {@link IncludedFamilyCollection }
     * 
     */
    public IncludedFamilyCollection createIncludedFamilyCollection() {
        return new IncludedFamilyCollection();
    }

    /**
     * Create an instance of {@link ModelYearMappingCollection }
     * 
     */
    public ModelYearMappingCollection createModelYearMappingCollection() {
        return new ModelYearMappingCollection();
    }

    /**
     * Create an instance of {@link FeatureApplicabilityInfoType }
     * 
     */
    public FeatureApplicabilityInfoType createFeatureApplicabilityInfoType() {
        return new FeatureApplicabilityInfoType();
    }

    /**
     * Create an instance of {@link BrochureModelDerivativeCollection }
     * 
     */
    public BrochureModelDerivativeCollection createBrochureModelDerivativeCollection() {
        return new BrochureModelDerivativeCollection();
    }

    /**
     * Create an instance of {@link TableRuleBodyRowCollection }
     * 
     */
    public TableRuleBodyRowCollection createTableRuleBodyRowCollection() {
        return new TableRuleBodyRowCollection();
    }

    /**
     * Create an instance of {@link TableRuleBodyRowCellCollection }
     * 
     */
    public TableRuleBodyRowCellCollection createTableRuleBodyRowCellCollection() {
        return new TableRuleBodyRowCellCollection();
    }

    /**
     * Create an instance of {@link FeatureApplicabilitySpanType }
     * 
     */
    public FeatureApplicabilitySpanType createFeatureApplicabilitySpanType() {
        return new FeatureApplicabilitySpanType();
    }

    /**
     * Create an instance of {@link FeatureApplicabilityType }
     * 
     */
    public FeatureApplicabilityType createFeatureApplicabilityType() {
        return new FeatureApplicabilityType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigitAceImportType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.configit.com/ace/import", name = "ConfigitAceImport")
    public JAXBElement<ConfigitAceImportType> createConfigitAceImport(ConfigitAceImportType value) {
        return new JAXBElement<ConfigitAceImportType>(_ConfigitAceImport_QNAME, ConfigitAceImportType.class, null, value);
    }

}
