//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OnFailureEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OnFailureEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="Closed"/>
 *     &lt;enumeration value="NonPromotable"/>
 *     &lt;enumeration value="Open"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OnFailureEnum", namespace = "http://schemas.configit.com/ace/import/v1")
@XmlEnum
public enum OnFailureEnum {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Closed")
    CLOSED("Closed"),
    @XmlEnumValue("NonPromotable")
    NON_PROMOTABLE("NonPromotable"),
    @XmlEnumValue("Open")
    OPEN("Open");
    private final String value;

    OnFailureEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OnFailureEnum fromValue(String v) {
        for (OnFailureEnum c: OnFailureEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
