//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PackRuleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PackRuleType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.configit.com/ace/import/v1/productrange}RuleHeaderType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Body" type="{http://schemas.configit.com/ace/import/v1/productrange}PackRuleIncludedFeatureCollection"/>
 *       &lt;/sequence>
 *       &lt;attribute name="PackFeature" use="required" type="{http://schemas.configit.com/ace/import/v1}CodeType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PackRuleType", namespace = "http://schemas.configit.com/ace/import/v1/productrange", propOrder = {
    "body"
})
public class PackRuleType
    extends RuleHeaderType
{

    @XmlElement(name = "Body")
    protected PackRuleIncludedFeatureCollection body;
    @XmlAttribute(name = "PackFeature", required = true)
    protected String packFeature;

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link PackRuleIncludedFeatureCollection }
     *     
     */
    public PackRuleIncludedFeatureCollection getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackRuleIncludedFeatureCollection }
     *     
     */
    public void setBody(PackRuleIncludedFeatureCollection value) {
        this.body = value;
    }

    /**
     * Gets the value of the packFeature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackFeature() {
        return packFeature;
    }

    /**
     * Sets the value of the packFeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackFeature(String value) {
        this.packFeature = value;
    }

}
