//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.configit.com/ace/import/v1/library", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.output;
