//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PostImportValidationOptionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PostImportValidationOptionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="CompileProductRanges" type="{http://schemas.configit.com/ace/import/v1}CompileProductRangesType" minOccurs="0"/>
 *         &lt;element name="PreventPromotionIfMasterChanged" type="{http://schemas.configit.com/ace/import/v1}PreventPromotionIfMasterChangedType" minOccurs="0"/>
 *         &lt;element name="CreateWorkItem" type="{http://schemas.configit.com/ace/import/v1}CreateWorkItemType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PostImportValidationOptionsType", namespace = "http://schemas.configit.com/ace/import/v1", propOrder = {
    "compileProductRanges",
    "preventPromotionIfMasterChanged",
    "createWorkItem"
})
public class PostImportValidationOptionsType {

    @XmlElement(name = "CompileProductRanges")
    protected CompileProductRangesType compileProductRanges;
    @XmlElement(name = "PreventPromotionIfMasterChanged")
    protected PreventPromotionIfMasterChangedType preventPromotionIfMasterChanged;
    @XmlElement(name = "CreateWorkItem")
    protected CreateWorkItemType createWorkItem;

    /**
     * Gets the value of the compileProductRanges property.
     * 
     * @return
     *     possible object is
     *     {@link CompileProductRangesType }
     *     
     */
    public CompileProductRangesType getCompileProductRanges() {
        return compileProductRanges;
    }

    /**
     * Sets the value of the compileProductRanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompileProductRangesType }
     *     
     */
    public void setCompileProductRanges(CompileProductRangesType value) {
        this.compileProductRanges = value;
    }

    /**
     * Gets the value of the preventPromotionIfMasterChanged property.
     * 
     * @return
     *     possible object is
     *     {@link PreventPromotionIfMasterChangedType }
     *     
     */
    public PreventPromotionIfMasterChangedType getPreventPromotionIfMasterChanged() {
        return preventPromotionIfMasterChanged;
    }

    /**
     * Sets the value of the preventPromotionIfMasterChanged property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreventPromotionIfMasterChangedType }
     *     
     */
    public void setPreventPromotionIfMasterChanged(PreventPromotionIfMasterChangedType value) {
        this.preventPromotionIfMasterChanged = value;
    }

    /**
     * Gets the value of the createWorkItem property.
     * 
     * @return
     *     possible object is
     *     {@link CreateWorkItemType }
     *     
     */
    public CreateWorkItemType getCreateWorkItem() {
        return createWorkItem;
    }

    /**
     * Sets the value of the createWorkItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateWorkItemType }
     *     
     */
    public void setCreateWorkItem(CreateWorkItemType value) {
        this.createWorkItem = value;
    }

}
