//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductRangeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductRangeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Basics" type="{http://schemas.configit.com/ace/import/v1/productrange}BasicsType" minOccurs="0"/>
 *         &lt;element name="Programmes" type="{http://schemas.configit.com/ace/import/v1/productrange}ProgrammeCollection" minOccurs="0"/>
 *         &lt;element name="Events" type="{http://schemas.configit.com/ace/import/v1/productrange}EventCollection" minOccurs="0"/>
 *         &lt;element name="FeatureAssociations" type="{http://schemas.configit.com/ace/import/v1/productrange}ProductRangeFeatureAssociationCollection" minOccurs="0"/>
 *         &lt;element name="ModelYearMappings" type="{http://schemas.configit.com/ace/import/v1/productrange}ModelYearMappingCollection" minOccurs="0"/>
 *         &lt;element name="BrochureModels" type="{http://schemas.configit.com/ace/import/v1/productrange}BrochureModelCollection" minOccurs="0"/>
 *         &lt;element name="MarketAvailability" type="{http://schemas.configit.com/ace/import/v1/productrange}MarketAvailabilitySpanCollection" minOccurs="0"/>
 *         &lt;element name="FeatureApplicability" type="{http://schemas.configit.com/ace/import/v1/productrange}FeatureApplicabilityType" minOccurs="0"/>
 *         &lt;element name="Rules" type="{http://schemas.configit.com/ace/import/v1/productrange}RuleType" minOccurs="0"/>
 *         &lt;element name="SellableUnits" type="{http://schemas.configit.com/ace/import/v1/productrange}SellableUnitsType" minOccurs="0"/>
 *         &lt;element name="DefaultConfiguratorLayout" type="{http://schemas.configit.com/ace/import/v1/productrange}DefaultConfiguratorLayoutType" minOccurs="0"/>
 *         &lt;element name="ProductRangeProperties" type="{http://schemas.configit.com/ace/import/v1/productrange}ProductRangePropertiesType" minOccurs="0"/>
 *         &lt;element name="DeleteModelYearMappings" type="{http://schemas.configit.com/ace/import/v1/delete}DeleteModelYearMappingCollection" minOccurs="0"/>
 *         &lt;element name="DeleteRules" type="{http://schemas.configit.com/ace/import/v1/delete}DeleteRulesCollection" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Code" use="required" type="{http://schemas.configit.com/ace/import/v1}CodeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductRangeType", namespace = "http://schemas.configit.com/ace/import/v1/productrange", propOrder = {
    "basics",
    "programmes",
    "events",
    "featureAssociations",
    "modelYearMappings",
    "brochureModels",
    "marketAvailability",
    "featureApplicability",
    "rules",
    "sellableUnits",
    "defaultConfiguratorLayout",
    "productRangeProperties",
    "deleteModelYearMappings",
    "deleteRules"
})
public class ProductRangeType {

    @XmlElement(name = "Basics")
    protected BasicsType basics;
    @XmlElement(name = "Programmes")
    protected ProgrammeCollection programmes;
    @XmlElement(name = "Events")
    protected EventCollection events;
    @XmlElement(name = "FeatureAssociations")
    protected ProductRangeFeatureAssociationCollection featureAssociations;
    @XmlElement(name = "ModelYearMappings")
    protected ModelYearMappingCollection modelYearMappings;
    @XmlElement(name = "BrochureModels")
    protected BrochureModelCollection brochureModels;
    @XmlElement(name = "MarketAvailability")
    protected MarketAvailabilitySpanCollection marketAvailability;
    @XmlElement(name = "FeatureApplicability")
    protected FeatureApplicabilityType featureApplicability;
    @XmlElement(name = "Rules")
    protected RuleType rules;
    @XmlElement(name = "SellableUnits")
    protected SellableUnitsType sellableUnits;
    @XmlElement(name = "DefaultConfiguratorLayout")
    protected DefaultConfiguratorLayoutType defaultConfiguratorLayout;
    @XmlElement(name = "ProductRangeProperties")
    protected ProductRangePropertiesType productRangeProperties;
    @XmlElement(name = "DeleteModelYearMappings")
    protected DeleteModelYearMappingCollection deleteModelYearMappings;
    @XmlElement(name = "DeleteRules")
    protected DeleteRulesCollection deleteRules;
    @XmlAttribute(name = "Code", required = true)
    protected String code;

    /**
     * Gets the value of the basics property.
     * 
     * @return
     *     possible object is
     *     {@link BasicsType }
     *     
     */
    public BasicsType getBasics() {
        return basics;
    }

    /**
     * Sets the value of the basics property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicsType }
     *     
     */
    public void setBasics(BasicsType value) {
        this.basics = value;
    }

    /**
     * Gets the value of the programmes property.
     * 
     * @return
     *     possible object is
     *     {@link ProgrammeCollection }
     *     
     */
    public ProgrammeCollection getProgrammes() {
        return programmes;
    }

    /**
     * Sets the value of the programmes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgrammeCollection }
     *     
     */
    public void setProgrammes(ProgrammeCollection value) {
        this.programmes = value;
    }

    /**
     * Gets the value of the events property.
     * 
     * @return
     *     possible object is
     *     {@link EventCollection }
     *     
     */
    public EventCollection getEvents() {
        return events;
    }

    /**
     * Sets the value of the events property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventCollection }
     *     
     */
    public void setEvents(EventCollection value) {
        this.events = value;
    }

    /**
     * Gets the value of the featureAssociations property.
     * 
     * @return
     *     possible object is
     *     {@link ProductRangeFeatureAssociationCollection }
     *     
     */
    public ProductRangeFeatureAssociationCollection getFeatureAssociations() {
        return featureAssociations;
    }

    /**
     * Sets the value of the featureAssociations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductRangeFeatureAssociationCollection }
     *     
     */
    public void setFeatureAssociations(ProductRangeFeatureAssociationCollection value) {
        this.featureAssociations = value;
    }

    /**
     * Gets the value of the modelYearMappings property.
     * 
     * @return
     *     possible object is
     *     {@link ModelYearMappingCollection }
     *     
     */
    public ModelYearMappingCollection getModelYearMappings() {
        return modelYearMappings;
    }

    /**
     * Sets the value of the modelYearMappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelYearMappingCollection }
     *     
     */
    public void setModelYearMappings(ModelYearMappingCollection value) {
        this.modelYearMappings = value;
    }

    /**
     * Gets the value of the brochureModels property.
     * 
     * @return
     *     possible object is
     *     {@link BrochureModelCollection }
     *     
     */
    public BrochureModelCollection getBrochureModels() {
        return brochureModels;
    }

    /**
     * Sets the value of the brochureModels property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrochureModelCollection }
     *     
     */
    public void setBrochureModels(BrochureModelCollection value) {
        this.brochureModels = value;
    }

    /**
     * Gets the value of the marketAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link MarketAvailabilitySpanCollection }
     *     
     */
    public MarketAvailabilitySpanCollection getMarketAvailability() {
        return marketAvailability;
    }

    /**
     * Sets the value of the marketAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketAvailabilitySpanCollection }
     *     
     */
    public void setMarketAvailability(MarketAvailabilitySpanCollection value) {
        this.marketAvailability = value;
    }

    /**
     * Gets the value of the featureApplicability property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureApplicabilityType }
     *     
     */
    public FeatureApplicabilityType getFeatureApplicability() {
        return featureApplicability;
    }

    /**
     * Sets the value of the featureApplicability property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureApplicabilityType }
     *     
     */
    public void setFeatureApplicability(FeatureApplicabilityType value) {
        this.featureApplicability = value;
    }

    /**
     * Gets the value of the rules property.
     * 
     * @return
     *     possible object is
     *     {@link RuleType }
     *     
     */
    public RuleType getRules() {
        return rules;
    }

    /**
     * Sets the value of the rules property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleType }
     *     
     */
    public void setRules(RuleType value) {
        this.rules = value;
    }

    /**
     * Gets the value of the sellableUnits property.
     * 
     * @return
     *     possible object is
     *     {@link SellableUnitsType }
     *     
     */
    public SellableUnitsType getSellableUnits() {
        return sellableUnits;
    }

    /**
     * Sets the value of the sellableUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link SellableUnitsType }
     *     
     */
    public void setSellableUnits(SellableUnitsType value) {
        this.sellableUnits = value;
    }

    /**
     * Gets the value of the defaultConfiguratorLayout property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultConfiguratorLayoutType }
     *     
     */
    public DefaultConfiguratorLayoutType getDefaultConfiguratorLayout() {
        return defaultConfiguratorLayout;
    }

    /**
     * Sets the value of the defaultConfiguratorLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultConfiguratorLayoutType }
     *     
     */
    public void setDefaultConfiguratorLayout(DefaultConfiguratorLayoutType value) {
        this.defaultConfiguratorLayout = value;
    }

    /**
     * Gets the value of the productRangeProperties property.
     * 
     * @return
     *     possible object is
     *     {@link ProductRangePropertiesType }
     *     
     */
    public ProductRangePropertiesType getProductRangeProperties() {
        return productRangeProperties;
    }

    /**
     * Sets the value of the productRangeProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductRangePropertiesType }
     *     
     */
    public void setProductRangeProperties(ProductRangePropertiesType value) {
        this.productRangeProperties = value;
    }

    /**
     * Gets the value of the deleteModelYearMappings property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteModelYearMappingCollection }
     *     
     */
    public DeleteModelYearMappingCollection getDeleteModelYearMappings() {
        return deleteModelYearMappings;
    }

    /**
     * Sets the value of the deleteModelYearMappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteModelYearMappingCollection }
     *     
     */
    public void setDeleteModelYearMappings(DeleteModelYearMappingCollection value) {
        this.deleteModelYearMappings = value;
    }

    /**
     * Gets the value of the deleteRules property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteRulesCollection }
     *     
     */
    public DeleteRulesCollection getDeleteRules() {
        return deleteRules;
    }

    /**
     * Sets the value of the deleteRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteRulesCollection }
     *     
     */
    public void setDeleteRules(DeleteRulesCollection value) {
        this.deleteRules = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

}
