//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductRangeFeatureAssociationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductRangeFeatureAssociationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.configit.com/ace/import/v1/library}FeatureCodeType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Effectivities" type="{http://schemas.configit.com/ace/import/v1/productrange}EffectivityCollection"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Priority" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductRangeFeatureAssociationType", namespace = "http://schemas.configit.com/ace/import/v1/productrange", propOrder = {
    "effectivities"
})
public class ProductRangeFeatureAssociationType
    extends FeatureCodeType
{

    @XmlElement(name = "Effectivities")
    protected EffectivityCollection effectivities;
    @XmlAttribute(name = "Priority", required = true)
    protected BigInteger priority;

    /**
     * Gets the value of the effectivities property.
     * 
     * @return
     *     possible object is
     *     {@link EffectivityCollection }
     *     
     */
    public EffectivityCollection getEffectivities() {
        return effectivities;
    }

    /**
     * Sets the value of the effectivities property.
     * 
     * @param value
     *     allowed object is
     *     {@link EffectivityCollection }
     *     
     */
    public void setEffectivities(EffectivityCollection value) {
        this.effectivities = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPriority(BigInteger value) {
        this.priority = value;
    }

}
