//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PropertyValueCollection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropertyValueCollection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="StringProperty" type="{http://schemas.configit.com/ace/import/v1}StringPropertyValueType"/>
 *         &lt;element name="BooleanProperty" type="{http://schemas.configit.com/ace/import/v1}BooleanPropertyValueType"/>
 *         &lt;element name="DateTimeProperty" type="{http://schemas.configit.com/ace/import/v1}DateTimePropertyValueType"/>
 *         &lt;element name="DecimalProperty" type="{http://schemas.configit.com/ace/import/v1}DecimalPropertyValueType"/>
 *         &lt;element name="IntegerProperty" type="{http://schemas.configit.com/ace/import/v1}IntegerPropertyValueType"/>
 *         &lt;element name="LongProperty" type="{http://schemas.configit.com/ace/import/v1}LongPropertyValueType"/>
 *         &lt;element name="ShortProperty" type="{http://schemas.configit.com/ace/import/v1}ShortPropertyValueType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyValueCollection", namespace = "http://schemas.configit.com/ace/import/v1", propOrder = {
    "stringPropertyOrBooleanPropertyOrDateTimeProperty"
})
public class PropertyValueCollection {

    @XmlElements({
        @XmlElement(name = "StringProperty", type = StringPropertyValueType.class),
        @XmlElement(name = "BooleanProperty", type = BooleanPropertyValueType.class),
        @XmlElement(name = "DateTimeProperty", type = DateTimePropertyValueType.class),
        @XmlElement(name = "DecimalProperty", type = DecimalPropertyValueType.class),
        @XmlElement(name = "IntegerProperty", type = IntegerPropertyValueType.class),
        @XmlElement(name = "LongProperty", type = LongPropertyValueType.class),
        @XmlElement(name = "ShortProperty", type = ShortPropertyValueType.class)
    })
    protected List<PropertyValueType> stringPropertyOrBooleanPropertyOrDateTimeProperty;

    /**
     * Gets the value of the stringPropertyOrBooleanPropertyOrDateTimeProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stringPropertyOrBooleanPropertyOrDateTimeProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStringPropertyOrBooleanPropertyOrDateTimeProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringPropertyValueType }
     * {@link BooleanPropertyValueType }
     * {@link DateTimePropertyValueType }
     * {@link DecimalPropertyValueType }
     * {@link IntegerPropertyValueType }
     * {@link LongPropertyValueType }
     * {@link ShortPropertyValueType }
     * 
     * 
     */
    public List<PropertyValueType> getStringPropertyOrBooleanPropertyOrDateTimeProperty() {
        if (stringPropertyOrBooleanPropertyOrDateTimeProperty == null) {
            stringPropertyOrBooleanPropertyOrDateTimeProperty = new ArrayList<PropertyValueType>();
        }
        return this.stringPropertyOrBooleanPropertyOrDateTimeProperty;
    }

}
