//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RuleHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RuleHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="PropertyValues" type="{http://schemas.configit.com/ace/import/v1}PropertyValueCollection"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Code" use="required" type="{http://schemas.configit.com/ace/import/v1/productrange}RuleCodeType" />
 *       &lt;attribute name="Description" use="required" type="{http://schemas.configit.com/ace/import/v1}DescriptionType" />
 *       &lt;attribute name="Intent" use="required" type="{http://schemas.configit.com/ace/import/v1/productrange}RuleIntentEnum" />
 *       &lt;attribute name="StartEvent" type="{http://schemas.configit.com/ace/import/v1/productrange}EventCodeType" />
 *       &lt;attribute name="EndEvent" type="{http://schemas.configit.com/ace/import/v1/productrange}EventCodeType" />
 *       &lt;attribute name="IsEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="IsLocked" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RuleHeaderType", namespace = "http://schemas.configit.com/ace/import/v1/productrange", propOrder = {
    "propertyValues"
})
@XmlSeeAlso({
    PackRuleType.class,
    TextRuleType.class,
    TableRuleType.class
})
public class RuleHeaderType {

    @XmlElement(name = "PropertyValues")
    protected PropertyValueCollection propertyValues;
    @XmlAttribute(name = "Code", required = true)
    protected String code;
    @XmlAttribute(name = "Description", required = true)
    protected String description;
    @XmlAttribute(name = "Intent", required = true)
    protected RuleIntentEnum intent;
    @XmlAttribute(name = "StartEvent")
    protected String startEvent;
    @XmlAttribute(name = "EndEvent")
    protected String endEvent;
    @XmlAttribute(name = "IsEnabled")
    protected Boolean isEnabled;
    @XmlAttribute(name = "IsLocked")
    protected Boolean isLocked;

    /**
     * Gets the value of the propertyValues property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueCollection }
     *     
     */
    public PropertyValueCollection getPropertyValues() {
        return propertyValues;
    }

    /**
     * Sets the value of the propertyValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueCollection }
     *     
     */
    public void setPropertyValues(PropertyValueCollection value) {
        this.propertyValues = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the intent property.
     * 
     * @return
     *     possible object is
     *     {@link RuleIntentEnum }
     *     
     */
    public RuleIntentEnum getIntent() {
        return intent;
    }

    /**
     * Sets the value of the intent property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleIntentEnum }
     *     
     */
    public void setIntent(RuleIntentEnum value) {
        this.intent = value;
    }

    /**
     * Gets the value of the startEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartEvent() {
        return startEvent;
    }

    /**
     * Sets the value of the startEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartEvent(String value) {
        this.startEvent = value;
    }

    /**
     * Gets the value of the endEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndEvent() {
        return endEvent;
    }

    /**
     * Sets the value of the endEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndEvent(String value) {
        this.endEvent = value;
    }

    /**
     * Gets the value of the isEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsEnabled() {
        if (isEnabled == null) {
            return true;
        } else {
            return isEnabled;
        }
    }

    /**
     * Sets the value of the isEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsEnabled(Boolean value) {
        this.isEnabled = value;
    }

    /**
     * Gets the value of the isLocked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsLocked() {
        if (isLocked == null) {
            return false;
        } else {
            return isLocked;
        }
    }

    /**
     * Sets the value of the isLocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsLocked(Boolean value) {
        this.isLocked = value;
    }

}
