//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RuleValidationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RuleValidationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Validation" use="required" type="{http://schemas.configit.com/ace/import/v1}ValidationActionEnum" />
 *       &lt;attribute name="AllowAceRules" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RuleValidationType", namespace = "http://schemas.configit.com/ace/import/v1")
public class RuleValidationType {

    @XmlAttribute(name = "Validation", required = true)
    protected ValidationActionEnum validation;
    @XmlAttribute(name = "AllowAceRules", required = true)
    protected boolean allowAceRules;

    /**
     * Gets the value of the validation property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationActionEnum }
     *     
     */
    public ValidationActionEnum getValidation() {
        return validation;
    }

    /**
     * Sets the value of the validation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationActionEnum }
     *     
     */
    public void setValidation(ValidationActionEnum value) {
        this.validation = value;
    }

    /**
     * Gets the value of the allowAceRules property.
     * 
     */
    public boolean isAllowAceRules() {
        return allowAceRules;
    }

    /**
     * Sets the value of the allowAceRules property.
     * 
     */
    public void setAllowAceRules(boolean value) {
        this.allowAceRules = value;
    }

}
