//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SellableUnitsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SellableUnitsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="DefiningFeatureFamilies" type="{http://schemas.configit.com/ace/import/v1/library}FamilyCodeCollection"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SellableUnitsType", namespace = "http://schemas.configit.com/ace/import/v1/productrange", propOrder = {
    "definingFeatureFamilies"
})
public class SellableUnitsType {

    @XmlElement(name = "DefiningFeatureFamilies")
    protected FamilyCodeCollection definingFeatureFamilies;

    /**
     * Gets the value of the definingFeatureFamilies property.
     * 
     * @return
     *     possible object is
     *     {@link FamilyCodeCollection }
     *     
     */
    public FamilyCodeCollection getDefiningFeatureFamilies() {
        return definingFeatureFamilies;
    }

    /**
     * Sets the value of the definingFeatureFamilies property.
     * 
     * @param value
     *     allowed object is
     *     {@link FamilyCodeCollection }
     *     
     */
    public void setDefiningFeatureFamilies(FamilyCodeCollection value) {
        this.definingFeatureFamilies = value;
    }

}
