//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TableRuleBodyRowType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TableRuleBodyRowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="Cells" type="{http://schemas.configit.com/ace/import/v1/productrange}TableRuleBodyRowCellCollection"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RowFeature" use="required" type="{http://schemas.configit.com/ace/import/v1}CodeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TableRuleBodyRowType", namespace = "http://schemas.configit.com/ace/import/v1/productrange", propOrder = {
    "cells"
})
public class TableRuleBodyRowType {

    @XmlElement(name = "Cells")
    protected List<TableRuleBodyRowCellCollection> cells;
    @XmlAttribute(name = "RowFeature", required = true)
    protected String rowFeature;

    /**
     * Gets the value of the cells property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cells property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCells().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TableRuleBodyRowCellCollection }
     * 
     * 
     */
    public List<TableRuleBodyRowCellCollection> getCells() {
        if (cells == null) {
            cells = new ArrayList<TableRuleBodyRowCellCollection>();
        }
        return this.cells;
    }

    /**
     * Gets the value of the rowFeature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowFeature() {
        return rowFeature;
    }

    /**
     * Sets the value of the rowFeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowFeature(String value) {
        this.rowFeature = value;
    }

}
