//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 03:28:23 PM IST 
//


package com.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TableRuleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TableRuleType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.configit.com/ace/import/v1/productrange}RuleHeaderType">
 *       &lt;sequence>
 *         &lt;element name="Columns" type="{http://schemas.configit.com/ace/import/v1/library}FamilyCodeCollection"/>
 *         &lt;element name="Rows" type="{http://schemas.configit.com/ace/import/v1/library}FamilyCodeCollection"/>
 *         &lt;element name="Body" type="{http://schemas.configit.com/ace/import/v1/productrange}TableRuleBodyRowCollection"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TableRuleType", namespace = "http://schemas.configit.com/ace/import/v1/productrange", propOrder = {
    "columns",
    "rows",
    "body"
})
public class TableRuleType
    extends RuleHeaderType
{

    @XmlElement(name = "Columns", required = true)
    protected FamilyCodeCollection columns;
    @XmlElement(name = "Rows", required = true)
    protected FamilyCodeCollection rows;
    @XmlElement(name = "Body", required = true)
    protected TableRuleBodyRowCollection body;

    /**
     * Gets the value of the columns property.
     * 
     * @return
     *     possible object is
     *     {@link FamilyCodeCollection }
     *     
     */
    public FamilyCodeCollection getColumns() {
        return columns;
    }

    /**
     * Sets the value of the columns property.
     * 
     * @param value
     *     allowed object is
     *     {@link FamilyCodeCollection }
     *     
     */
    public void setColumns(FamilyCodeCollection value) {
        this.columns = value;
    }

    /**
     * Gets the value of the rows property.
     * 
     * @return
     *     possible object is
     *     {@link FamilyCodeCollection }
     *     
     */
    public FamilyCodeCollection getRows() {
        return rows;
    }

    /**
     * Sets the value of the rows property.
     * 
     * @param value
     *     allowed object is
     *     {@link FamilyCodeCollection }
     *     
     */
    public void setRows(FamilyCodeCollection value) {
        this.rows = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link TableRuleBodyRowCollection }
     *     
     */
    public TableRuleBodyRowCollection getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableRuleBodyRowCollection }
     *     
     */
    public void setBody(TableRuleBodyRowCollection value) {
        this.body = value;
    }

}
