//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 07:10:29 PM IST 
//


package com.input;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.input.sampleimport package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.input.sampleimport
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConfigitAceImport }
     * 
     */
    public ConfigitAceImport createConfigitAceImport() {
        return new ConfigitAceImport();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges }
     * 
     */
    public ConfigitAceImport.ProductRanges createConfigitAceImportProductRanges() {
        return new ConfigitAceImport.ProductRanges();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange createConfigitAceImportProductRangesProductRange() {
        return new ConfigitAceImport.ProductRanges.ProductRange();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.Rules }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.Rules createConfigitAceImportProductRangesProductRangeRules() {
        return new ConfigitAceImport.ProductRanges.ProductRange.Rules();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.Rules.TextRules }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.Rules.TextRules createConfigitAceImportProductRangesProductRangeRulesTextRules() {
        return new ConfigitAceImport.ProductRanges.ProductRange.Rules.TextRules();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability createConfigitAceImportProductRangesProductRangeFeatureApplicability() {
        return new ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans createConfigitAceImportProductRangesProductRangeFeatureApplicabilityFeatureApplicabilitySpans() {
        return new ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan createConfigitAceImportProductRangesProductRangeFeatureApplicabilityFeatureApplicabilitySpansFeatureApplicabilitySpan() {
        return new ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.Features }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.Features createConfigitAceImportProductRangesProductRangeFeatureApplicabilityFeatureApplicabilitySpansFeatureApplicabilitySpanFeatures() {
        return new ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.Features();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.BrochureModelDerivatives }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.BrochureModelDerivatives createConfigitAceImportProductRangesProductRangeFeatureApplicabilityFeatureApplicabilitySpansFeatureApplicabilitySpanBrochureModelDerivatives() {
        return new ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.BrochureModelDerivatives();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.Markets }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.Markets createConfigitAceImportProductRangesProductRangeFeatureApplicabilityFeatureApplicabilitySpansFeatureApplicabilitySpanMarkets() {
        return new ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.Markets();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.IncludedFamilies }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.IncludedFamilies createConfigitAceImportProductRangesProductRangeFeatureApplicabilityIncludedFamilies() {
        return new ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.IncludedFamilies();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.MarketAvailability }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.MarketAvailability createConfigitAceImportProductRangesProductRangeMarketAvailability() {
        return new ConfigitAceImport.ProductRanges.ProductRange.MarketAvailability();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.MarketAvailability.MarketAvailabilitySpan }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.MarketAvailability.MarketAvailabilitySpan createConfigitAceImportProductRangesProductRangeMarketAvailabilityMarketAvailabilitySpan() {
        return new ConfigitAceImport.ProductRanges.ProductRange.MarketAvailability.MarketAvailabilitySpan();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.MarketAvailability.MarketAvailabilitySpan.BrochureModelDerivatives }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.MarketAvailability.MarketAvailabilitySpan.BrochureModelDerivatives createConfigitAceImportProductRangesProductRangeMarketAvailabilityMarketAvailabilitySpanBrochureModelDerivatives() {
        return new ConfigitAceImport.ProductRanges.ProductRange.MarketAvailability.MarketAvailabilitySpan.BrochureModelDerivatives();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.BrochureModels }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.BrochureModels createConfigitAceImportProductRangesProductRangeBrochureModels() {
        return new ConfigitAceImport.ProductRanges.ProductRange.BrochureModels();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.BrochureModels.BrochureModel }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.BrochureModels.BrochureModel createConfigitAceImportProductRangesProductRangeBrochureModelsBrochureModel() {
        return new ConfigitAceImport.ProductRanges.ProductRange.BrochureModels.BrochureModel();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.BrochureModels.BrochureModel.Derivatives }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.BrochureModels.BrochureModel.Derivatives createConfigitAceImportProductRangesProductRangeBrochureModelsBrochureModelDerivatives() {
        return new ConfigitAceImport.ProductRanges.ProductRange.BrochureModels.BrochureModel.Derivatives();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.BrochureModels.BrochureModel.BrochureModelDefiningFeatures }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.BrochureModels.BrochureModel.BrochureModelDefiningFeatures createConfigitAceImportProductRangesProductRangeBrochureModelsBrochureModelBrochureModelDefiningFeatures() {
        return new ConfigitAceImport.ProductRanges.ProductRange.BrochureModels.BrochureModel.BrochureModelDefiningFeatures();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.FeatureAssociations }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.FeatureAssociations createConfigitAceImportProductRangesProductRangeFeatureAssociations() {
        return new ConfigitAceImport.ProductRanges.ProductRange.FeatureAssociations();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.FeatureAssociations.Feature }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.FeatureAssociations.Feature createConfigitAceImportProductRangesProductRangeFeatureAssociationsFeature() {
        return new ConfigitAceImport.ProductRanges.ProductRange.FeatureAssociations.Feature();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.FeatureAssociations.Feature.Effectivities }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.FeatureAssociations.Feature.Effectivities createConfigitAceImportProductRangesProductRangeFeatureAssociationsFeatureEffectivities() {
        return new ConfigitAceImport.ProductRanges.ProductRange.FeatureAssociations.Feature.Effectivities();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.Events }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.Events createConfigitAceImportProductRangesProductRangeEvents() {
        return new ConfigitAceImport.ProductRanges.ProductRange.Events();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.Basics }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.Basics createConfigitAceImportProductRangesProductRangeBasics() {
        return new ConfigitAceImport.ProductRanges.ProductRange.Basics();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.Basics.BrochureModelDefiningFeatureFamilies }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.Basics.BrochureModelDefiningFeatureFamilies createConfigitAceImportProductRangesProductRangeBasicsBrochureModelDefiningFeatureFamilies() {
        return new ConfigitAceImport.ProductRanges.ProductRange.Basics.BrochureModelDefiningFeatureFamilies();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library }
     * 
     */
    public ConfigitAceImport.Library createConfigitAceImportLibrary() {
        return new ConfigitAceImport.Library();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.ConfiguratorLayouts }
     * 
     */
    public ConfigitAceImport.Library.ConfiguratorLayouts createConfigitAceImportLibraryConfiguratorLayouts() {
        return new ConfigitAceImport.Library.ConfiguratorLayouts();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout }
     * 
     */
    public ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout createConfigitAceImportLibraryConfiguratorLayoutsConfiguratorLayout() {
        return new ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs }
     * 
     */
    public ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs createConfigitAceImportLibraryConfiguratorLayoutsConfiguratorLayoutLayoutTabs() {
        return new ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab }
     * 
     */
    public ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab createConfigitAceImportLibraryConfiguratorLayoutsConfiguratorLayoutLayoutTabsLayoutTab() {
        return new ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections }
     * 
     */
    public ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections createConfigitAceImportLibraryConfiguratorLayoutsConfiguratorLayoutLayoutTabsLayoutTabLayoutSections() {
        return new ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections.LayoutSection }
     * 
     */
    public ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections.LayoutSection createConfigitAceImportLibraryConfiguratorLayoutsConfiguratorLayoutLayoutTabsLayoutTabLayoutSectionsLayoutSection() {
        return new ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections.LayoutSection();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections.LayoutSection.LayoutFeatureFamilies }
     * 
     */
    public ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections.LayoutSection.LayoutFeatureFamilies createConfigitAceImportLibraryConfiguratorLayoutsConfiguratorLayoutLayoutTabsLayoutTabLayoutSectionsLayoutSectionLayoutFeatureFamilies() {
        return new ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections.LayoutSection.LayoutFeatureFamilies();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections.LayoutSection.LayoutFeatureFamilies.LayoutFeatureFamily }
     * 
     */
    public ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections.LayoutSection.LayoutFeatureFamilies.LayoutFeatureFamily createConfigitAceImportLibraryConfiguratorLayoutsConfiguratorLayoutLayoutTabsLayoutTabLayoutSectionsLayoutSectionLayoutFeatureFamiliesLayoutFeatureFamily() {
        return new ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections.LayoutSection.LayoutFeatureFamilies.LayoutFeatureFamily();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections.LayoutSection.LayoutFeatureFamilies.LayoutFeatureFamily.LayoutFeatures }
     * 
     */
    public ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections.LayoutSection.LayoutFeatureFamilies.LayoutFeatureFamily.LayoutFeatures createConfigitAceImportLibraryConfiguratorLayoutsConfiguratorLayoutLayoutTabsLayoutTabLayoutSectionsLayoutSectionLayoutFeatureFamiliesLayoutFeatureFamilyLayoutFeatures() {
        return new ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections.LayoutSection.LayoutFeatureFamilies.LayoutFeatureFamily.LayoutFeatures();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.MarketGroups }
     * 
     */
    public ConfigitAceImport.Library.MarketGroups createConfigitAceImportLibraryMarketGroups() {
        return new ConfigitAceImport.Library.MarketGroups();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.MarketGroups.MarketGroup }
     * 
     */
    public ConfigitAceImport.Library.MarketGroups.MarketGroup createConfigitAceImportLibraryMarketGroupsMarketGroup() {
        return new ConfigitAceImport.Library.MarketGroups.MarketGroup();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.MarketGroups.MarketGroup.Brands }
     * 
     */
    public ConfigitAceImport.Library.MarketGroups.MarketGroup.Brands createConfigitAceImportLibraryMarketGroupsMarketGroupBrands() {
        return new ConfigitAceImport.Library.MarketGroups.MarketGroup.Brands();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.MarketGroups.MarketGroup.Markets }
     * 
     */
    public ConfigitAceImport.Library.MarketGroups.MarketGroup.Markets createConfigitAceImportLibraryMarketGroupsMarketGroupMarkets() {
        return new ConfigitAceImport.Library.MarketGroups.MarketGroup.Markets();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.Markets }
     * 
     */
    public ConfigitAceImport.Library.Markets createConfigitAceImportLibraryMarkets() {
        return new ConfigitAceImport.Library.Markets();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.Markets.Market }
     * 
     */
    public ConfigitAceImport.Library.Markets.Market createConfigitAceImportLibraryMarketsMarket() {
        return new ConfigitAceImport.Library.Markets.Market();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.Markets.Market.Languages }
     * 
     */
    public ConfigitAceImport.Library.Markets.Market.Languages createConfigitAceImportLibraryMarketsMarketLanguages() {
        return new ConfigitAceImport.Library.Markets.Market.Languages();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.Brands }
     * 
     */
    public ConfigitAceImport.Library.Brands createConfigitAceImportLibraryBrands() {
        return new ConfigitAceImport.Library.Brands();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.Features }
     * 
     */
    public ConfigitAceImport.Library.Features createConfigitAceImportLibraryFeatures() {
        return new ConfigitAceImport.Library.Features();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.FeatureFamilies }
     * 
     */
    public ConfigitAceImport.Library.FeatureFamilies createConfigitAceImportLibraryFeatureFamilies() {
        return new ConfigitAceImport.Library.FeatureFamilies();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.Languages }
     * 
     */
    public ConfigitAceImport.Library.Languages createConfigitAceImportLibraryLanguages() {
        return new ConfigitAceImport.Library.Languages();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.PostImportValidationOptions }
     * 
     */
    public ConfigitAceImport.PostImportValidationOptions createConfigitAceImportPostImportValidationOptions() {
        return new ConfigitAceImport.PostImportValidationOptions();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.DataValidationOptions }
     * 
     */
    public ConfigitAceImport.DataValidationOptions createConfigitAceImportDataValidationOptions() {
        return new ConfigitAceImport.DataValidationOptions();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ImportDetails }
     * 
     */
    public ConfigitAceImport.ImportDetails createConfigitAceImportImportDetails() {
        return new ConfigitAceImport.ImportDetails();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.DefaultConfiguratorLayout }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.DefaultConfiguratorLayout createConfigitAceImportProductRangesProductRangeDefaultConfiguratorLayout() {
        return new ConfigitAceImport.ProductRanges.ProductRange.DefaultConfiguratorLayout();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.Rules.TextRules.TextRule }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.Rules.TextRules.TextRule createConfigitAceImportProductRangesProductRangeRulesTextRulesTextRule() {
        return new ConfigitAceImport.ProductRanges.ProductRange.Rules.TextRules.TextRule();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.Features.Feature }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.Features.Feature createConfigitAceImportProductRangesProductRangeFeatureApplicabilityFeatureApplicabilitySpansFeatureApplicabilitySpanFeaturesFeature() {
        return new ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.Features.Feature();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.BrochureModelDerivatives.BrochureModelDerivative }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.BrochureModelDerivatives.BrochureModelDerivative createConfigitAceImportProductRangesProductRangeFeatureApplicabilityFeatureApplicabilitySpansFeatureApplicabilitySpanBrochureModelDerivativesBrochureModelDerivative() {
        return new ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.BrochureModelDerivatives.BrochureModelDerivative();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.Markets.Market }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.Markets.Market createConfigitAceImportProductRangesProductRangeFeatureApplicabilityFeatureApplicabilitySpansFeatureApplicabilitySpanMarketsMarket() {
        return new ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.FeatureApplicabilitySpans.FeatureApplicabilitySpan.Markets.Market();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.IncludedFamilies.Family }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.IncludedFamilies.Family createConfigitAceImportProductRangesProductRangeFeatureApplicabilityIncludedFamiliesFamily() {
        return new ConfigitAceImport.ProductRanges.ProductRange.FeatureApplicability.IncludedFamilies.Family();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.MarketAvailability.MarketAvailabilitySpan.BrochureModelDerivatives.BrochureModelDerivative }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.MarketAvailability.MarketAvailabilitySpan.BrochureModelDerivatives.BrochureModelDerivative createConfigitAceImportProductRangesProductRangeMarketAvailabilityMarketAvailabilitySpanBrochureModelDerivativesBrochureModelDerivative() {
        return new ConfigitAceImport.ProductRanges.ProductRange.MarketAvailability.MarketAvailabilitySpan.BrochureModelDerivatives.BrochureModelDerivative();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.BrochureModels.BrochureModel.Derivatives.Feature }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.BrochureModels.BrochureModel.Derivatives.Feature createConfigitAceImportProductRangesProductRangeBrochureModelsBrochureModelDerivativesFeature() {
        return new ConfigitAceImport.ProductRanges.ProductRange.BrochureModels.BrochureModel.Derivatives.Feature();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.BrochureModels.BrochureModel.BrochureModelDefiningFeatures.Feature }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.BrochureModels.BrochureModel.BrochureModelDefiningFeatures.Feature createConfigitAceImportProductRangesProductRangeBrochureModelsBrochureModelBrochureModelDefiningFeaturesFeature() {
        return new ConfigitAceImport.ProductRanges.ProductRange.BrochureModels.BrochureModel.BrochureModelDefiningFeatures.Feature();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.FeatureAssociations.Feature.Effectivities.Effectivity }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.FeatureAssociations.Feature.Effectivities.Effectivity createConfigitAceImportProductRangesProductRangeFeatureAssociationsFeatureEffectivitiesEffectivity() {
        return new ConfigitAceImport.ProductRanges.ProductRange.FeatureAssociations.Feature.Effectivities.Effectivity();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.Events.Event }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.Events.Event createConfigitAceImportProductRangesProductRangeEventsEvent() {
        return new ConfigitAceImport.ProductRanges.ProductRange.Events.Event();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.ProductRanges.ProductRange.Basics.BrochureModelDefiningFeatureFamilies.Family }
     * 
     */
    public ConfigitAceImport.ProductRanges.ProductRange.Basics.BrochureModelDefiningFeatureFamilies.Family createConfigitAceImportProductRangesProductRangeBasicsBrochureModelDefiningFeatureFamiliesFamily() {
        return new ConfigitAceImport.ProductRanges.ProductRange.Basics.BrochureModelDefiningFeatureFamilies.Family();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections.LayoutSection.LayoutFeatureFamilies.LayoutFeatureFamily.LayoutFeatures.LayoutFeature }
     * 
     */
    public ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections.LayoutSection.LayoutFeatureFamilies.LayoutFeatureFamily.LayoutFeatures.LayoutFeature createConfigitAceImportLibraryConfiguratorLayoutsConfiguratorLayoutLayoutTabsLayoutTabLayoutSectionsLayoutSectionLayoutFeatureFamiliesLayoutFeatureFamilyLayoutFeaturesLayoutFeature() {
        return new ConfigitAceImport.Library.ConfiguratorLayouts.ConfiguratorLayout.LayoutTabs.LayoutTab.LayoutSections.LayoutSection.LayoutFeatureFamilies.LayoutFeatureFamily.LayoutFeatures.LayoutFeature();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.MarketGroups.MarketGroup.Brands.Brand }
     * 
     */
    public ConfigitAceImport.Library.MarketGroups.MarketGroup.Brands.Brand createConfigitAceImportLibraryMarketGroupsMarketGroupBrandsBrand() {
        return new ConfigitAceImport.Library.MarketGroups.MarketGroup.Brands.Brand();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.MarketGroups.MarketGroup.Markets.Market }
     * 
     */
    public ConfigitAceImport.Library.MarketGroups.MarketGroup.Markets.Market createConfigitAceImportLibraryMarketGroupsMarketGroupMarketsMarket() {
        return new ConfigitAceImport.Library.MarketGroups.MarketGroup.Markets.Market();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.Markets.Market.Languages.Language }
     * 
     */
    public ConfigitAceImport.Library.Markets.Market.Languages.Language createConfigitAceImportLibraryMarketsMarketLanguagesLanguage() {
        return new ConfigitAceImport.Library.Markets.Market.Languages.Language();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.Brands.Brand }
     * 
     */
    public ConfigitAceImport.Library.Brands.Brand createConfigitAceImportLibraryBrandsBrand() {
        return new ConfigitAceImport.Library.Brands.Brand();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.Features.Feature }
     * 
     */
    public ConfigitAceImport.Library.Features.Feature createConfigitAceImportLibraryFeaturesFeature() {
        return new ConfigitAceImport.Library.Features.Feature();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.FeatureFamilies.FeatureFamily }
     * 
     */
    public ConfigitAceImport.Library.FeatureFamilies.FeatureFamily createConfigitAceImportLibraryFeatureFamiliesFeatureFamily() {
        return new ConfigitAceImport.Library.FeatureFamilies.FeatureFamily();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.Library.Languages.Language }
     * 
     */
    public ConfigitAceImport.Library.Languages.Language createConfigitAceImportLibraryLanguagesLanguage() {
        return new ConfigitAceImport.Library.Languages.Language();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.PostImportValidationOptions.CreateWorkItem }
     * 
     */
    public ConfigitAceImport.PostImportValidationOptions.CreateWorkItem createConfigitAceImportPostImportValidationOptionsCreateWorkItem() {
        return new ConfigitAceImport.PostImportValidationOptions.CreateWorkItem();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.DataValidationOptions.ModelYearMapping }
     * 
     */
    public ConfigitAceImport.DataValidationOptions.ModelYearMapping createConfigitAceImportDataValidationOptionsModelYearMapping() {
        return new ConfigitAceImport.DataValidationOptions.ModelYearMapping();
    }

    /**
     * Create an instance of {@link ConfigitAceImport.DataValidationOptions.Rule }
     * 
     */
    public ConfigitAceImport.DataValidationOptions.Rule createConfigitAceImportDataValidationOptionsRule() {
        return new ConfigitAceImport.DataValidationOptions.Rule();
    }

}
